import { ObjectType } from "../types/interfaces";

export const medicalExaminations: string[] = [
  "Audiogramme",
  "Audiométrie",
  "Prothèse auditive",
  "Audiophonologie",
  "Auriculothérapie",
  "Endométriose",
  "Médecine du surpoids et de l'obésité",
  "Médecine générale",
  "Médecine préventive",
  "Médecine traditionnelle chinoise (MTC)",
  "Naturopathie",
  "Phytothérapie",
  "Sevrage tabagique",
  "Suivi de grossesse",
  "Évaluation et traitement de la douleur",
  "Homéopathie",
  "Mésothérapie",
  "Ostéopathie",
  "Alimentation de la femme enceinte",
  "Allaitement",
  "Conseil en nutrition",
  "Diététique pédiatrique",
  "Nutrition du sportif",
  "Obésité",
  "Rééquilibrage alimentaire",
  "Soins de support oncologique",
  "Surpoids",
  "Éducation au diabète",
  "Éducation thérapeutique",
  "Diététique énergétique",
  "Drainage lymphatique",
  "Luxopuncture",
  "Micronutrition",
  "Nutrithérapie",
  "Conseil en diététique",
  "Diététique pédiatrique",
  "Suivi du sportif",
  "Troubles du comportement alimentaire",
  "Accompagnement diététique post-chirurgie bariatrique",
  "Nutrition",
  "Naturopathie",
  "Phytothérapie",
  "Rééducation fonctionnelle",
  "Auxiliaire médical en pratique avancée",
  "Bilan cognitif",
  "Bilan postural",
  "Rééducation des patients Alzheimer",
  "Rééducation neurologique",
  "Conseil en aménagement du lieu de vie",
  "Conseil en prévention des chutes",
  "Bilan psychomoteur",
  "Rééducation de l'écriture",
  "Kinésithérapie",
  "Kinésithérapie respiratoire et cardio-vasculaire",
  "K-Tape",
  "Pressothérapie",
  "Traitement de la bronchiolite",
  "Kinésithérapie du sport",
  "Suivi du sportif",
  "Rééducation de l'épaule",
  "Rééducation du membre inférieur",
  "Rééducation du genou",
  "Rééducation de la cheville",
  "Rééducation du pied",
  "Rééducation du dos",
  "Rééducation du bassin",
  "Rééducation du membre supérieur",
  "Rééducation fonctionnelle",
  "Rééducation post-opératoire du ligament croisé antérieur",
  "Rééducation ora-faciale ou maxillo-faciale",
  "Ostéopathie crânienne",
  "Ostéopathie du sport",
  "Ostéopathie maxillo-faciale et oro-faciale",
  "Ostéopathie myofasciale",
  "Ostéopathie structurelle",
  "Ostéopathie viscérale",
  "Ostéopathie de la femme",
  "Ostéopathie de la femme enceinte",
  "Ostéopathie pédiatrique",
  "Ostéopathie hémodynamique",
  "Dépistage COVID-19 test PCR",
  "Dépistage COVID-19 test antigénique",
  "Injection",
  "Vaccination (hors COVID-19)",
  "Stomathérapie",
  "Traitement des cicatrices",
  "Vaccination antigrippale (Grippe)",
  "Education thérapeutique",
  "Bilan orthophonique",
  "Rééducation orthophonique",
  "Rééducation de la déglutition",
  "Rééducation des patients Alzheimer",
  "Rééducation oro-faciale",
  "Rééducation maxillo-faciale",
  "Bilan orthoptique",
  "Orthoptie pédiatrique",
  "Bilan de la vue",
  "Strabologie",
  "Posturologie",
  "Champ visuel",
  "Bilan et rééducation basse vision",
  "Bilan et rééducation neurovisuels",
  "Examens de la vision et des couleurs",
  "Bilan podologique",
  "Podologie",
  "Podologie du sport",
  "Pédicurie",
  "Semelles orthopédiques",
  "Bilan postural",
  "Orthoplastie",
  "Orthèse plantaire",
  "Bilan psychomoteur",
  "Thérapie psycho-corporelle",
  "Addictologie",
  "Bilan psychomoteur",
  "Périnatalité",
  "Remédiation cognitive",
  "Rééducation des patients Alzheimer",
  "Thérapie psycho-corporelle",
  "Thérapie psycho-émotionnelle",
  "Accompagnement au développement personnel",
  "Approche psychosomatique",
  "Gestion du stress",
  "Psychologie clinique",
  "Psychologie positive",
  "Psychotraumatologie",
  "Souffrance au travail",
  "Thérapie analytique",
  "Thérapie d'orientation psychanalytique",
  "Thérapie troubles anxieux",
  "Victimologie",
  "Accompagnement psychologique pour trouble de l'identité de genre",
  "Psychanalyse",
  "Psychologie de l'adulte",
  "Psychothérapie",
  "Souffrance au travail",
  "Thérapie EMDR",
  "Test de QI (Quotient Intellectuel)",
  "Contraception",
  "Frottis",
  "Implant contraceptif",
  "Maternité",
  "Pilule contraceptive",
  "Pose de stérilet",
  "Préparation à la naissance",
  "Suivi de grossesse",
  "Suivi en gynécologie",
  "Vaccination HPV (Papillomavirus)",
  "Dépistage de papillomavirus humain (HPV)",
  "Sage-femme",
  "Interruption volontaire de grossesse (IVG) médicamenteuse",
  "Planning familial",
  "Echographie",
  "Echographiste",
  "Echographie de datation",
  "Echographie gynécologique et obstétricale",
  "Échographie obstétricale",
  "Accouchement physiologique",
  "Acupuncture",
  "Allaitement",
  "Endométriose",
  "Maternité",
  "Ménopause",
  "PMA/AMP - FIV - Fertilité",
  "Sevrage tabagique",
  "Suivi de grossesse",
  "Allergie",
  "Allergie pollens",
  "Allergie respiratoire",
  "Allergologie",
  "Allergie",
  "Allergie pollens",
  "Allergie respiratoire",
  "Allergologie",
  "Artérite",
  "Doppler",
  "Médecine vasculaire",
  "Phlébologie",
  "Sclérothérapie des varices",
  "Échodoppler vasculaire",
  "Phlébite",
  "Varices",
  "Ulcère des jambes",
  "Artériopathie",
  "Artérite",
  "Doppler",
  "Médecine vasculaire",
  "Insuffisance cardiaque",
  "Trouble du rythme",
  "Échodoppler vasculaire",
  "Hypertension artérielle",
  "Epreuve d'effort",
  "Coronarographie",
  "Rythmologue",
  "Palpitations",
  "Malaise",
  "Perte de connaissance",
  "Examens cardiologiques",
  "Cardiologie du sport",
  "Artérite",
  "Extrasystole",
  "Stent",
  "Douleurs à la poitrine",
  "douleurs thoraciques",
  "Essoufflement",
  "Dyspnée",
  "Oedème des jambes",
  "Oedème pulmonaire",
  "Chirurgie de la thyroïde",
  "Chirurgie des cancers avec technique coelioscopique et robotique",
  "Chirurgie cancérologique",
  "Chirurgie de la paroi abdominale",
  "Chirurgie des voies biliaires",
  "Chirurgie digestive",
  "Chirurgie du foie",
  "Cancer de l'estomac",
  "Chirurgie du rectum",
  "Chirurgie bariatrique",
  "Hernie",
  "Chirurgie de l'obésité",
  "Chirurgie herniaire",
  "Lithiase biliare",
  "Chirurgie pariétale",
  "Chirurgie proctologique",
  "Hémorroides",
  "Cancer de la vessie",
  "Cancer de la prostate",
  "Cancer du rein",
  "Cancérologie urologique",
  "Chirurgie de la lithiase urinaire",
  "Chirurgie de la prostate",
  "Chirurgie de l'incontinence urinaire",
  "Chirurgie pelvienne",
  "Exploration urodynamique",
  "Prolapsus ou descente d'organe",
  "Colique néphrétique   calculs rénaux",
  "Prostate",
  "Incontinence urinaire",
  "Difficultés à uriner",
  "Trouble de l'erection",
  "Sang dans les urines",
  "Chirurgie de l'épaule",
  "Chirurgie de la cheville",
  "Chirurgie de la hanche",
  "Chirurgie du genou",
  "Chirurgie de la main",
  "Chirurgie du poignet",
  "Chirurgie du coude",
  "Chirurgie des ligaments croisés",
  "Arthrose",
  "Arthroscopie du genou",
  "Chirurgie arthroscopique",
  "Arthroscopie",
  "Infiltration",
  "Canal carpien",
  "Cervicalgie",
  "Infiltration",
  "Lombalgie",
  "Médecine du sport",
  "Névralgie cervico-brachiale",
  "Orthopédie",
  "Traumatologie pédiatrique",
  "Chirurgie du pied",
  "Chirurgie du rachis",
  "Fracture",
  "Difficultés à la marche",
  "Douleurs dorsales",
  "Douleurs lombaires",
  "Douleurs cervicales",
  "Chirurgie cancérologique",
  "Chirurgie de la paroi abdominale",
  "Chirurgie des voies biliaires",
  "Chirurgie digestive",
  "Chirurgie du foie",
  "Cancer de l'utérus",
  "Cancérologie du sein",
  "Cancérologie gynécologique",
  "Chirurgie esthétique",
  "Chirurgie plastique",
  "Injection",
  "Médecine esthétique",
  "Body lift",
  "Chirurgie dermatologique",
  "Chirurgie plastique et esthétique de la face et du cou",
  "Chirurgie du visage",
  "Chirurgie esthétique et réparation du sein",
  "Botox",
  "Lifting",
  "Chirurgie thoracique et cardio-vasculaire",
  "Chirurgie cardiaque",
  "Dissection aortique",
  "Pontage",
  "Chirurgie valvulaire",
  "Chirurgie cardiaque pédiatrique",
  "Chirurgie vasculaire",
  "Angiographie",
  "Bilan de la vue",
  "Chirurgie de la cataracte",
  "Chirurgie de la rétine",
  "Chirurgie ophtalmologique",
  "Chirurgie de la réfraction",
  "Chirurgien des paupières",
  "Cataracte",
  "Chirurgie des paupières",
  "Chirurgie Laser",
  "Chirurgie des voies lacrymales",
  "Chirurgie oculoplastique",
  "Douleurs aux yeux",
  "Baisse de la vue",
  "Infections à l'œil",
  "Conjonctivite",
  "Perte de la vue",
  "Paupières enflées",
  "Chirurgie de la thyroïde",
  "Chirurgie des glandes salivaires",
  "Chirurgie des sinus",
  "Chirurgie des tumeurs cutanées de la face et du cou",
  "Chirurgie endonasale",
  "Chirurgie orale",
  "ORL cancérologique",
  "ORL rhinologique",
  "Oto-rhino-laryngologie",
  "Otospongiose",
  "Polygraphie ventilatoire",
  "Rhinoplastie chirurgicale",
  "Ronflements",
  "Tympanoplastie",
  "Acouphènes",
  "Apnée du sommeil",
  "Chirurgie de l'oreille",
  "Chirurgie de la face et du cou",
  "Endoscopie",
  "ORL cancérologique",
  "ORL et chirurgie cervico-faciale",
  "Otite",
  "Mal aux oreilles",
  "ORL gériatrique",
  "ORL pédiatrique",
  "Perte de l'audition",
  "Bouchon d'oreille",
  "Chirurgie artérielle et veineuse",
  "Chirurgie des varices",
  "Chirurgie endovasculaire",
  "Ulcère de jambe",
  "Artériographie",
  "Artérite",
  "Chirurgie gynécologique",
  "Chirurgie sénologie",
  "Contraception",
  "Fibrome utérin",
  "Gynécologie médicale et obstétrique",
  "Gynécologue",
  "Suivi de grossesse",
  "Suivi en gynécologie",
  "Augmentation mammaire",
  "Chirurgie dermatologique",
  "Chirurgie esthétique et réparation du sein",
  "Chirurgie mammaire",
  "Implant mammaire",
  "Injection d'acide hyaluronique",
  "Injection de toxine botulique",
  "Lifting mammaire",
  "Lipoaspiration",
  "Lipofilling mammaire",
  "Otoplastie",
  "Plastie abdominale",
  "Plastie mammaire",
  "Réduction mammaire",
  "Liposuccion",
  "Augmentation mammaire",
  "Réduction mammaire",
  "Changement de prothèses mammaires",
  "Prothèses de mollet",
  "Blépharoplastie (chirurgie des paupières)",
  "Oreilles décollées",
  "Abdominoplastie (chirurgie du ventre)",
  "Augmentation mammaire par lipofilling (graisse)",
  "Cancer de l'utérus",
  "Chirurgie de la stérilité",
  "Chirurgie du sein",
  "Chirurgie gynécologique",
  "Chirurgie gynécologique et obstétrique",
  "Colposcopie",
  "Dépistage de papillomavirus humain (HPV)",
  "Endométriose",
  "Fibrome utérin",
  "Hystéroscopie",
  "Implant contraceptif",
  "Laser vaginal",
  "Pose de stérilet",
  "Cancer de l'utérus",
  "Cancérologie du sein",
  "Cancérologie gynécologique",
  "Chirurgie gynécologique",
  "Chirurgie gynécologique et obstétrique",
  "Bouffées de chaleur",
  "Chirurgie pelvienne",
  "Ménopause",
  "Chirurgie sénologie",
  "Coelioscopie",
  "Gynécologie médicale et obstétrique",
  "Gynécologue",
  "Suivi en gynécologie",
  "Pillule  contraception",
  "Chirurgie bariatrique",
  "Chirurgie de l'obésité",
  "Chirurgie générale",
  "Chirurgie herniaire",
  "Chirurgie hépato-biliaire",
  "Chirurgie pariétale",
  "Chirurgie proctologique",
  "Chirurgie cancérologique",
  "Hernie ombilicale ou ventrale",
  "Hernie inguinale",
  "Gros ventre ou diastasis",
  "Canal lombaire étroit",
  "Chirurgie de la colonne vertébrale et de la moelle épinière",
  "Chirurgie de la scoliose",
  "Chirurgie du rachis",
  "Hernie discale",
  "Névralgie cervico-brachiale",
  "Sciatique",
  "Spondylolisthésis",
  "Chirurgie du dos",
  "Chirurgie du dos et du rachis",
  "Chirurgie dermatologique",
  "Chirurgie des tumeurs cutanées de la face et du cou",
  "Médecine esthétique",
  "Grains de beauté",
  "Evaluation et traitement de la douleur",
  "Chirurgie crânienne et cérébrale",
  "Neurochirurgie du rachis",
  "Canal lombaire étroit",
  "Chirurgie de la colonne vertébrale et de la moelle épinière",
  "Hernie discale",
  "Sciatique",
  "Artériographie cérébrale",
  "tumeur cérébrale",
  "Allergie cutanée",
  "Chirurgie dermatologique",
  "Dermatologie chirurgicale",
  "Dermatologie esthétique",
  "Dermatologie laser",
  "Injections",
  "Injection d'acide hyaluronique",
  "Laser",
  "Laser dermatologique",
  "Laser médical",
  "Laser vasculaire",
  "Pratique esthétique",
  "Vénérologie",
  "Acné",
  "Dermatologie chirurgicale",
  "Dermatologie esthétique",
  "Dermatologie médicale",
  "Grains de beauté",
  "Injection de toxine botulique",
  "Maladies/infections sexuellement transmissibles (MST/IST)",
  "Mésothérapie",
  "Peeling",
  "Cryothérapie",
  "Dermatologie pédiatrique",
  "Laser CO2",
  "Laser ablatif",
  "Maladie de Verneuil (hidradénite suppurée)",
  "Mycose",
  "Mélanome",
  "Psoriasis",
  "Rosacée",
  "Verrue",
  "infection cutanée",
  "Angiome",
  "Couperose",
  "psoriasis",
  "Dermite séborrhéique",
  "Teigne",
  "Vitiligo",
  "Injection d'acide hyaluronique",
  "Microneedling",
  "Radiofréquence",
  "Boutons",
  "Diabétologie diabéte",
  "Endocrinologie diabétologie",
  "Adénome hypophysaire",
  "Pompe à insuline",
  "Endocrinologie diabétologie",
  "Médecine de la nutrition",
  "Diabète gestationnel",
  "Diabète Type 1",
  "Diabète Type 2",
  "Médecine du surpoids et de l'obésité",
  "Thyroide",
  "Insuffisance surrénalienne",
  "Endoscopie digestive",
  "Gastro-entérologie",
  "Proctologie",
  "Proctologie médicale",
  "Chirurgie proctologique",
  "Chirurgie du reﬂux gastro-œsophagien",
  "Reflux",
  "Trouble du transit (constipation, diarrhée…)",
  "Chirurgie viscérale",
  "Trouble digestif",
  "Hernie",
  "Coloscopie",
  "Hémorroides",
  "Trouble de la digestion",
  "Ulcère",
  "Vomissements",
  "Hernie hiatale",
  "Fibroscopie",
  "Anneau gastrique (ballon gastrique)",
  "Biologie génétique",
  "Bilan génétique",
  "Maladie héréditaire",
  "Maladie génétique",
  "Apnée du sommeil",
  "Gérontopsychiatrie",
  "Maladie de Parkinson",
  "Maladie d'Alzheimer",
  "Evaluation et traitement de la douleur",
  "Bilan gériatrique",
  "Bilan cognitif",
  "Bilan locomoteur",
  "Gérontologie",
  "Alzheimer",
  "Colposcopie",
  "Frottis",
  "holter ecg",
  "mapa holter tensionnel",
  "Grossesse pathologique",
  "Gynécologie médicale",
  "Gynécologie médicale et obstétrique",
  "Gynécologue",
  "Pose de stérilet",
  "Retrait de stérilet",
  "Suivi de grossesse",
  "Suivi en gynécologie",
  "Échographie de datation",
  "Échographie obstétricale",
  "Échographie pelvienne",
  "Frottis",
  "Maternité",
  "Gynécologie obstétrique",
  "Prolapsus ou descente d'organe",
  "PMA/AMP - FIV - Fertilité",
  "Échographie mammaire",
  "Hystéroscopie",
  "Echographie transvaginale",
  "Echographie de stimulation",
  "Chirurgie gynécologique",
  "Contraception  pilule",
  "Colposcopie",
  "Endométriose",
  "Interruption volontaire de grossesse (IVG) médicamenteuse",
  "Infertilité",
  "Bilan biologique d'amylose",
  "Bilan de coagulation",
  "Bilan de biologie HTA",
  "Bilan biologique vascularite",
  "Bilan d'insuffisance cardiaque",
  "Bilan immunologique",
  "Leucémie",
  "Anémie",
  "Carence en fer",
  "Lymphome",
  "Maladie de Biermer",
  "Bilan Hypogammaglobuline",
  "Bilan d'insuffisance rénale",
  "Bilan sanguin général - prise de sang",
  "Maladies du sang",
  "Maladie de Vaquez",
  "Purpura Thrombopénique Immunologique (PTI)",
  "Immunologie et hématologie pédiatrique",
  "Electrophorèse",
  "Immunologie",
  "Maladies auto-immunes et inflammatoires",
  "Immunodéficiences (acquises ou héréditaires)",
  "Médecine des maladies rares",
  "Immunothérapies",
  "Allergie",
  "Hépatite",
  "Maladies/infections sexuellement transmissibles (MST/IST)",
  "Médecine des voyages",
  "Prophylaxie pré-exposition (PrEP)",
  "VIH",
  "Vaccination (hors COVID-19)",
  "Centre de lutte anti-tuberculeuse",
  "Hépatite",
  "Médecine tropicale",
  "Médecine générale",
  "Médecine de l'enfant et de l'adolescent",
  "Médecine Générale",
  "Médecine des voyages",
  "Médecine du sport",
  "Fils tenseurs",
  "Greffe capillaire",
  "Injection d'acide hyaluronique",
  "Céphalée et migraine",
  "Mésothérapie",
  "Homéopathie",
  "Traumatologie du sport",
  "Vaccination (hors COVID-19)",
  "Vaccination COVID-19",
  "Apnée du sommeil",
  "Céphalée et migraine",
  "Médecine légale et expertises médicales",
  "Médecin agréé permis de conduire",
  "Injection",
  "Injection d'acide hyaluronique",
  "Laser esthétique",
  "Médecine esthétique",
  "Epilation laser",
  "Pratique esthétique",
  "Sophrologie",
  "Calculs rénaux",
  "Dialyse",
  "Hypertension artérielle",
  "Hématurie",
  "Insuffisance rénale",
  "Protéinurie",
  "Syndrome néphrotique",
  "Calculs rénaux",
  "Exploration rénale",
  "Transplantation rénale",
  "Immunologie",
  "Exploration neurologique",
  "Électromyogramme (EMG) des membres supérieurs et inférieurs",
  "Sclérose en plaques (SEP)",
  "Electromyogramme (EMG) des membres supérieurs",
  "Electromyogramme (EMG) des membres inférieurs",
  "Céphalée et migraine",
  "Exploration fonctionnelle neurologique",
  "Examens neurologiques",
  "Maladies neurodégénératives",
  "Maladie de Parkinson",
  "Maladies du corps de Lewy",
  "Rééducation neuromotrice",
  "Maladies neurologiques rares",
  "Alzheimer",
  "AVC AIT",
  "Cancérologie du sein.",
  "Chimiothérapie.",
  "Tumeur cérébrale.",
  "Cancérologie thoracique.",
  "ORL cancérologique.",
  "Chirurgie réfractive",
  "Chirurgie ophtalmique",
  "Chirurgie de la myopie",
  "Chirurgie de la presbytie",
  "Chirurgie de la cornée",
  "Chirurgie de l'hypermétropie",
  "Chirurgie du glaucome",
  "Chirurgie de l'astigmatisme",
  "Chirurgie de la cataracte",
  "DMLA (Dégénerescence Maculaire Liéée à l'Age)",
  "OCT",
  "LASIK",
  "Exploration ophtalmologique",
  "Glaucome",
  "Injection intravitréenne",
  "Lentilles de contact",
  "OCT",
  "Presbylasik",
  "Cataracte",
  "Bébé vision",
  "Champ visuel",
  "Suivi ophtalmologique",
  "Médecine de l'enfant et de l'adolescent",
  "Médecine du surpoids et de l'obésité pédiatrique",
  "Vaccination (hors COVID-19)",
  "Infectiologie pédiatrique",
  "Allergologie",
  "Néonatologie",
  "Troubles du sommeil",
  "Guidance parentale",
  "Allergologie pédiatrique",
  "Prise en charge de la douleur",
  "Allergie respiratoire",
  "Évaluation et traitement de la douleur",
  "Allergie alimentaire",
  "Allergie aux médicaments",
  "Allergie cutanée",
  "Allergie respiratoire",
  "Apnée du sommeil",
  "Apnée du sommeil de l'enfant",
  "Insomnie",
  "Médecine du sommeil",
  "Polygraphie nocturne",
  "Polysomnographie",
  "Ronflements",
  "Troubles du sommeil",
  "Polygraphie ventilatoire",
  "Vaccination",
  "cancer du poumon",
  "Bronchite chronique (BPCO)",
  "Bilan pneumologique et respiratoire",
  "Gaz du sang",
  "Test du sommeil (polygraphie, polysmnographie)",
  "Essouflements",

  "Thérapie cognitive et comportementale (TCC)",
  "Burn-out",
  "Psychiatrie polyvalente",
  "Psychothérapie",
  "Psychotraumatologie",
  "Thérapie troubles anxieux",
  "Trouble bipolaire",
  "Diagnostic bipolarité",
  "Diagnostic TDA / TDAH",
  "Tests psychiques",

  "Arthrose",
  "Cervicalgie",
  "Infiltration",
  "Médecine du sport",
  "Ostéoporose",
  "Rhumatisme inflammatoire",
  "Sciatique",
  "Tendinite",
  "Échographie ostéo-articulaire",
  "Polyarthrite",
  "Spondylarthrite",
  "Viscosupplémentation",
  "Infiltration écho-guidée",
  "Échographie ostéo-articulaire",
  "Chirurgie buccale",
  "Chirurgie dermatologique cervico-faciale",
  "Chirurgie des dents de sagesse",
  "Chirurgie des tumeurs cutanées de la face et du cou",
  "Chirurgie du visage",
  "Chirurgie maxillo-faciale",
  "Chirurgie orthognathique",
  "Chirurgie plastique et esthétique de la face et du cou",
  "Chirurgie pré-implantaire",
  "Implantologie",
  "Implantologie dentaire",
  "Stomatologie",
  "Bruxisme",
  "Chirurgie orale",
  "Greffe capillaire",
  "Injection",
  "Chirurgie des glandes salivaires",
  "Chirurgie pré-implantaire",
  "Chirurgien des paupières",
  "Greffe osseuse",
  "Médecine dentaire",
  "Implantologie",
  "Implantologie dentaire",
  "Chirurgie dentaire",
  "Couronne dentaire",
  "Stellite dentaire",
  "Dentisterie numérique",
  "Blanchiment des dents",
  "Chirurgie des dents de sagesse",
  "Extraction dentaire",
  "Greffe osseuse",
  "Carie",
  "Radio panoramique",
  "Radiographie dentaire",
  "Cône beam",
  "Détartrage",
  "Prothèse dentaire fixe ou amovible",
  "Prothèse sur implant",
  "Prophylaxie",
  "Facette dentaire",
  "Orthodontie pour adulte",
  "Orthodontie pédiatrique",
  "Orthopédie dento-faciale",
  "Alignement dentaire invisible",
  "Apnée du sommeil",
  "Appareil dentaire",
  "Blanchiment des dents",
  "Dysfonctionnement temporo-mandibulaire (DTM)",
  "Détartrage",
  "Gouttière dentaire",
  "Orthèse d'avancée mandibulaire (OAM)",
  "Radio panoramique",
  "Technique linguale",
  "Occlusodontie",
];

export const medicalExaminationsObj: ObjectType = {
  audiogramme: "Audiogramme",
  audiometrie: "Audiométrie",
  protheseAuditive: "Prothèse auditive",
  audiophonologie: "Audiophonologie",
  auriculotherapie: "Auriculothérapie",
  endometriose: "Endométriose",
  medecineDuSurpoidsEtDeLobesite: "Médecine du surpoids et de l'obésité",
  medecineGenerale: "Médecine Générale",
  medecinePreventive: "Médecine préventive",
  medecineTraditionnelleChinoiseMtc: "Médecine traditionnelle chinoise (MTC)",
  naturopathie: "Naturopathie",
  phytotherapie: "Phytothérapie",
  sevrageTabagique: "Sevrage tabagique",
  suiviDeGrossesse: "Suivi de grossesse",
  evaluationEtTraitementDeLaDouleur: "Évaluation et traitement de la douleur",
  homeopathie: "Homéopathie",
  mesotherapie: "Mésothérapie",
  osteopathie: "Ostéopathie",
  alimentationDeLaFemmeEnceinte: "Alimentation de la femme enceinte",
  allaitement: "Allaitement",
  conseilEnNutrition: "Conseil en nutrition",
  dietetiquePediatrique: "Diététique pédiatrique",
  nutritionDuSportif: "Nutrition du sportif",
  obesite: "Obésité",
  reequilibrageAlimentaire: "Rééquilibrage alimentaire",
  soinsDeSupportOncologique: "Soins de support oncologique",
  surpoids: "Surpoids",
  educationAuDiabete: "Éducation au diabète",
  educationTherapeutique: "Education thérapeutique",
  dietetiqueEnergetique: "Diététique énergétique",
  drainageLymphatique: "Drainage lymphatique",
  luxopuncture: "Luxopuncture",
  micronutrition: "Micronutrition",
  nutritherapie: "Nutrithérapie",
  conseilEnDietetique: "Conseil en diététique",
  suiviDuSportif: "Suivi du sportif",
  troublesDuComportementAlimentaire: "Troubles du comportement alimentaire",
  accompagnementDietetiquePostChirurgieBariatrique:
    "Accompagnement diététique post-chirurgie bariatrique",
  nutrition: "Nutrition",
  reeducationFonctionnelle: "Rééducation fonctionnelle",
  auxiliaireMedicalEnPratiqueAvancee: "Auxiliaire médical en pratique avancée",
  bilanCognitif: "Bilan cognitif",
  bilanPostural: "Bilan postural",
  reeducationDesPatientsAlzheimer: "Rééducation des patients Alzheimer",
  reeducationNeurologique: "Rééducation neurologique",
  conseilEnAmenagementDuLieuDeVie: "Conseil en aménagement du lieu de vie",
  conseilEnPreventionDesChutes: "Conseil en prévention des chutes",
  bilanPsychomoteur: "Bilan psychomoteur",
  reeducationDeLecriture: "Rééducation de l'écriture",
  kinesitherapie: "Kinésithérapie",
  kinesitherapieRespiratoireEtCardioVasculaire:
    "Kinésithérapie respiratoire et cardio-vasculaire",
  kTape: "K-Tape",
  pressotherapie: "Pressothérapie",
  traitementDeLaBronchiolite: "Traitement de la bronchiolite",
  kinesitherapieDuSport: "Kinésithérapie du sport",
  reeducationDeLepaule: "Rééducation de l'épaule",
  reeducationDuMembreInferieur: "Rééducation du membre inférieur",
  reeducationDuGenou: "Rééducation du genou",
  reeducationDeLaCheville: "Rééducation de la cheville",
  reeducationDuPied: "Rééducation du pied",
  reeducationDuDos: "Rééducation du dos",
  reeducationDuBassin: "Rééducation du bassin",
  reeducationDuMembreSuperieur: "Rééducation du membre supérieur",
  reeducationPostOperatoireDuLigamentCroiseAnterieur:
    "Rééducation post-opératoire du ligament croisé antérieur",
  reeducationOraFacialeOuMaxilloFaciale:
    "Rééducation ora-faciale ou maxillo-faciale",
  osteopathieCranienne: "Ostéopathie crânienne",
  osteopathieDuSport: "Ostéopathie du sport",
  osteopathieMaxilloFacialeEtOroFaciale:
    "Ostéopathie maxillo-faciale et oro-faciale",
  osteopathieMyofasciale: "Ostéopathie myofasciale",
  osteopathieStructurelle: "Ostéopathie structurelle",
  osteopathieViscerale: "Ostéopathie viscérale",
  osteopathieDeLaFemme: "Ostéopathie de la femme",
  osteopathieDeLaFemmeEnceinte: "Ostéopathie de la femme enceinte",
  osteopathiePediatrique: "Ostéopathie pédiatrique",
  osteopathieHemodynamique: "Ostéopathie hémodynamique",
  depistageCovid19TestPcr: "Dépistage COVID-19 test PCR",
  depistageCovid19TestAntigenique: "Dépistage COVID-19 test antigénique",
  injection: "Injection",
  vaccinationHorsCovid19: "Vaccination (hors COVID-19)",
  stomatherapie: "Stomathérapie",
  traitementDesCicatrices: "Traitement des cicatrices",
  vaccinationAntigrippaleGrippe: "Vaccination antigrippale (Grippe)",
  bilanOrthophonique: "Bilan orthophonique",
  reeducationOrthophonique: "Rééducation orthophonique",
  reeducationDeLaDeglutition: "Rééducation de la déglutition",
  reeducationOroFaciale: "Rééducation oro-faciale",
  reeducationMaxilloFaciale: "Rééducation maxillo-faciale",
  bilanOrthoptique: "Bilan orthoptique",
  orthoptiePediatrique: "Orthoptie pédiatrique",
  bilanDeLaVue: "Bilan de la vue",
  strabologie: "Strabologie",
  posturologie: "Posturologie",
  champVisuel: "Champ visuel",
  bilanEtReeducationBasseVision: "Bilan et rééducation basse vision",
  bilanEtReeducationNeurovisuels: "Bilan et rééducation neurovisuels",
  examensDeLaVisionEtDesCouleurs: "Examens de la vision et des couleurs",
  bilanPodologique: "Bilan podologique",
  podologie: "Podologie",
  podologieDuSport: "Podologie du sport",
  pedicurie: "Pédicurie",
  semellesOrthopediques: "Semelles orthopédiques",
  orthoplastie: "Orthoplastie",
  orthesePlantaire: "Orthèse plantaire",
  therapiePsychoCorporelle: "Thérapie psycho-corporelle",
  addictologie: "Addictologie",
  perinatalite: "Périnatalité",
  remediationCognitive: "Remédiation cognitive",
  therapiePsychoEmotionnelle: "Thérapie psycho-émotionnelle",
  accompagnementAuDeveloppementPersonnel:
    "Accompagnement au développement personnel",
  approchePsychosomatique: "Approche psychosomatique",
  gestionDuStress: "Gestion du stress",
  psychologieClinique: "Psychologie clinique",
  psychologiePositive: "Psychologie positive",
  psychotraumatologie: "Psychotraumatologie",
  souffranceAuTravail: "Souffrance au travail",
  therapieAnalytique: "Thérapie analytique",
  therapieDorientationPsychanalytique: "Thérapie d'orientation psychanalytique",
  therapieTroublesAnxieux: "Thérapie troubles anxieux",
  victimologie: "Victimologie",
  accompagnementPsychologiquePourTroubleDeLidentiteDeGenre:
    "Accompagnement psychologique pour trouble de l'identité de genre",
  psychanalyse: "Psychanalyse",
  psychologieDeLadulte: "Psychologie de l'adulte",
  psychotherapie: "Psychothérapie",
  therapieEmdr: "Thérapie EMDR",
  testDeQiQuotientIntellectuel: "Test de QI (Quotient Intellectuel)",
  contraception: "Contraception",
  frottis: "Frottis",
  implantContraceptif: "Implant contraceptif",
  maternite: "Maternité",
  piluleContraceptive: "Pilule contraceptive",
  poseDeSterilet: "Pose de stérilet",
  preparationALaNaissance: "Préparation à la naissance",
  suiviEnGynecologie: "Suivi en gynécologie",
  vaccinationHpvPapillomavirus: "Vaccination HPV (Papillomavirus)",
  depistageDePapillomavirusHumainHpv:
    "Dépistage de papillomavirus humain (HPV)",
  sageFemme: "Sage-femme",
  interruptionVolontaireDeGrossesseIvgMedicamenteuse:
    "Interruption volontaire de grossesse (IVG) médicamenteuse",
  planningFamilial: "Planning familial",
  echographie: "Echographie",
  echographiste: "Echographiste",
  echographieDeDatation: "Échographie de datation",
  echographieGynecologiqueEtObstetricale:
    "Echographie gynécologique et obstétricale",
  echographieObstetricale: "Échographie obstétricale",
  accouchementPhysiologique: "Accouchement physiologique",
  acupuncture: "Acupuncture",
  menopause: "Ménopause",
  pmaampFivFertilite: "PMA/AMP - FIV - Fertilité",
  allergie: "Allergie",
  allergiePollens: "Allergie pollens",
  allergieRespiratoire: "Allergie respiratoire",
  allergologie: "Allergologie",
  arterite: "Artérite",
  doppler: "Doppler",
  medecineVasculaire: "Médecine vasculaire",
  phlebologie: "Phlébologie",
  sclerotherapieDesVarices: "Sclérothérapie des varices",
  echodopplerVasculaire: "Échodoppler vasculaire",
  phlebite: "Phlébite",
  varices: "Varices",
  ulcereDesJambes: "Ulcère des jambes",
  arteriopathie: "Artériopathie",
  insuffisanceCardiaque: "Insuffisance cardiaque",
  troubleDuRythme: "Trouble du rythme",
  hypertensionArterielle: "Hypertension artérielle",
  epreuveDeffort: "Epreuve d'effort",
  coronarographie: "Coronarographie",
  rythmologue: "Rythmologue",
  palpitations: "Palpitations",
  malaise: "Malaise",
  perteDeConnaissance: "Perte de connaissance",
  examensCardiologiques: "Examens cardiologiques",
  cardiologieDuSport: "Cardiologie du sport",
  extrasystole: "Extrasystole",
  stent: "Stent",
  douleursALaPoitrine: "Douleurs à la poitrine",
  douleursThoraciques: "douleurs thoraciques",
  essoufflement: "Essoufflement",
  dyspnee: "Dyspnée",
  oedemeDesJambes: "Oedème des jambes",
  oedemePulmonaire: "Oedème pulmonaire",
  chirurgieDeLaThyroide: "Chirurgie de la thyroïde",
  chirurgieDesCancersAvecTechniqueCoelioscopiqueEtRobotique:
    "Chirurgie des cancers avec technique coelioscopique et robotique",
  chirurgieCancerologique: "Chirurgie cancérologique",
  chirurgieDeLaParoiAbdominale: "Chirurgie de la paroi abdominale",
  chirurgieDesVoiesBiliaires: "Chirurgie des voies biliaires",
  chirurgieDigestive: "Chirurgie digestive",
  chirurgieDuFoie: "Chirurgie du foie",
  cancerDeLestomac: "Cancer de l'estomac",
  chirurgieDuRectum: "Chirurgie du rectum",
  chirurgieBariatrique: "Chirurgie bariatrique",
  hernie: "Hernie",
  chirurgieDeLobesite: "Chirurgie de l'obésité",
  chirurgieHerniaire: "Chirurgie herniaire",
  lithiaseBiliare: "Lithiase biliare",
  chirurgieParietale: "Chirurgie pariétale",
  chirurgieProctologique: "Chirurgie proctologique",
  hemorroides: "Hémorroides",
  cancerDeLaVessie: "Cancer de la vessie",
  cancerDeLaProstate: "Cancer de la prostate",
  cancerDuRein: "Cancer du rein",
  cancerologieUrologique: "Cancérologie urologique",
  chirurgieDeLaLithiaseUrinaire: "Chirurgie de la lithiase urinaire",
  chirurgieDeLaProstate: "Chirurgie de la prostate",
  chirurgieDeLincontinenceUrinaire: "Chirurgie de l'incontinence urinaire",
  chirurgiePelvienne: "Chirurgie pelvienne",
  explorationUrodynamique: "Exploration urodynamique",
  prolapsusOuDescenteDorgane: "Prolapsus ou descente d'organe",
  coliqueNephretiqueCalculsRenaux: "Colique néphrétique   calculs rénaux",
  prostate: "Prostate",
  incontinenceUrinaire: "Incontinence urinaire",
  difficultesAUriner: "Difficultés à uriner",
  troubleDeLerection: "Trouble de l'erection",
  sangDansLesUrines: "Sang dans les urines",
  chirurgieDeLepaule: "Chirurgie de l'épaule",
  chirurgieDeLaCheville: "Chirurgie de la cheville",
  chirurgieDeLaHanche: "Chirurgie de la hanche",
  chirurgieDuGenou: "Chirurgie du genou",
  chirurgieDeLaMain: "Chirurgie de la main",
  chirurgieDuPoignet: "Chirurgie du poignet",
  chirurgieDuCoude: "Chirurgie du coude",
  chirurgieDesLigamentsCroises: "Chirurgie des ligaments croisés",
  arthrose: "Arthrose",
  arthroscopieDuGenou: "Arthroscopie du genou",
  chirurgieArthroscopique: "Chirurgie arthroscopique",
  arthroscopie: "Arthroscopie",
  infiltration: "Infiltration",
  canalCarpien: "Canal carpien",
  cervicalgie: "Cervicalgie",
  lombalgie: "Lombalgie",
  medecineDuSport: "Médecine du sport",
  nevralgieCervicoBrachiale: "Névralgie cervico-brachiale",
  orthopedie: "Orthopédie",
  traumatologiePediatrique: "Traumatologie pédiatrique",
  chirurgieDuPied: "Chirurgie du pied",
  chirurgieDuRachis: "Chirurgie du rachis",
  fracture: "Fracture",
  difficultesALaMarche: "Difficultés à la marche",
  douleursDorsales: "Douleurs dorsales",
  douleursLombaires: "Douleurs lombaires",
  douleursCervicales: "Douleurs cervicales",
  cancerDeLuterus: "Cancer de l'utérus",
  cancerologieDuSein: "Cancérologie du sein.",
  cancerologieGynecologique: "Cancérologie gynécologique",
  chirurgieEsthetique: "Chirurgie esthétique",
  chirurgiePlastique: "Chirurgie plastique",
  medecineEsthetique: "Médecine esthétique",
  bodyLift: "Body lift",
  chirurgieDermatologique: "Chirurgie dermatologique",
  chirurgiePlastiqueEtEsthetiqueDeLaFaceEtDuCou:
    "Chirurgie plastique et esthétique de la face et du cou",
  chirurgieDuVisage: "Chirurgie du visage",
  chirurgieEsthetiqueEtReparationDuSein:
    "Chirurgie esthétique et réparation du sein",
  botox: "Botox",
  lifting: "Lifting",
  chirurgieThoraciqueEtCardioVasculaire:
    "Chirurgie thoracique et cardio-vasculaire",
  chirurgieCardiaque: "Chirurgie cardiaque",
  dissectionAortique: "Dissection aortique",
  pontage: "Pontage",
  chirurgieValvulaire: "Chirurgie valvulaire",
  chirurgieCardiaquePediatrique: "Chirurgie cardiaque pédiatrique",
  chirurgieVasculaire: "Chirurgie vasculaire",
  angiographie: "Angiographie",
  chirurgieDeLaCataracte: "Chirurgie de la cataracte",
  chirurgieDeLaRetine: "Chirurgie de la rétine",
  chirurgieOphtalmologique: "Chirurgie ophtalmologique",
  chirurgieDeLaRefraction: "Chirurgie de la réfraction",
  chirurgienDesPaupieres: "Chirurgien des paupières",
  cataracte: "Cataracte",
  chirurgieDesPaupieres: "Chirurgie des paupières",
  chirurgieLaser: "Chirurgie Laser",
  chirurgieDesVoiesLacrymales: "Chirurgie des voies lacrymales",
  chirurgieOculoplastique: "Chirurgie oculoplastique",
  douleursAuxYeux: "Douleurs aux yeux",
  baisseDeLaVue: "Baisse de la vue",
  infectionsALil: "Infections à l'œil",
  conjonctivite: "Conjonctivite",
  perteDeLaVue: "Perte de la vue",
  paupieresEnflees: "Paupières enflées",
  chirurgieDesGlandesSalivaires: "Chirurgie des glandes salivaires",
  chirurgieDesSinus: "Chirurgie des sinus",
  chirurgieDesTumeursCutaneesDeLaFaceEtDuCou:
    "Chirurgie des tumeurs cutanées de la face et du cou",
  chirurgieEndonasale: "Chirurgie endonasale",
  chirurgieOrale: "Chirurgie orale",
  orlCancerologique: "ORL cancérologique.",
  orlRhinologique: "ORL rhinologique",
  otoRhinoLaryngologie: "Oto-rhino-laryngologie",
  otospongiose: "Otospongiose",
  polygraphieVentilatoire: "Polygraphie ventilatoire",
  rhinoplastieChirurgicale: "Rhinoplastie chirurgicale",
  ronflements: "Ronflements",
  tympanoplastie: "Tympanoplastie",
  acouphenes: "Acouphènes",
  apneeDuSommeil: "Apnée du sommeil",
  chirurgieDeLoreille: "Chirurgie de l'oreille",
  chirurgieDeLaFaceEtDuCou: "Chirurgie de la face et du cou",
  endoscopie: "Endoscopie",
  orlEtChirurgieCervicoFaciale: "ORL et chirurgie cervico-faciale",
  otite: "Otite",
  malAuxOreilles: "Mal aux oreilles",
  orlGeriatrique: "ORL gériatrique",
  orlPediatrique: "ORL pédiatrique",
  perteDeLaudition: "Perte de l'audition",
  bouchonDoreille: "Bouchon d'oreille",
  chirurgieArterielleEtVeineuse: "Chirurgie artérielle et veineuse",
  chirurgieDesVarices: "Chirurgie des varices",
  chirurgieEndovasculaire: "Chirurgie endovasculaire",
  ulcereDeJambe: "Ulcère de jambe",
  arteriographie: "Artériographie",
  chirurgieGynecologique: "Chirurgie gynécologique",
  chirurgieSenologie: "Chirurgie sénologie",
  fibromeUterin: "Fibrome utérin",
  gynecologieMedicaleEtObstetrique: "Gynécologie médicale et obstétrique",
  gynecologue: "Gynécologue",
  augmentationMammaire: "Augmentation mammaire",
  chirurgieMammaire: "Chirurgie mammaire",
  implantMammaire: "Implant mammaire",
  injectionDacideHyaluronique: "Injection d'acide hyaluronique",
  injectionDeToxineBotulique: "Injection de toxine botulique",
  liftingMammaire: "Lifting mammaire",
  lipoaspiration: "Lipoaspiration",
  lipofillingMammaire: "Lipofilling mammaire",
  otoplastie: "Otoplastie",
  plastieAbdominale: "Plastie abdominale",
  plastieMammaire: "Plastie mammaire",
  reductionMammaire: "Réduction mammaire",
  liposuccion: "Liposuccion",
  changementDeProthesesMammaires: "Changement de prothèses mammaires",
  prothesesDeMollet: "Prothèses de mollet",
  blepharoplastieChirurgieDesPaupieres:
    "Blépharoplastie (chirurgie des paupières)",
  oreillesDecollees: "Oreilles décollées",
  abdominoplastieChirurgieDuVentre: "Abdominoplastie (chirurgie du ventre)",
  augmentationMammaireParLipofillingGraisse:
    "Augmentation mammaire par lipofilling (graisse)",
  chirurgieDeLaSterilite: "Chirurgie de la stérilité",
  chirurgieDuSein: "Chirurgie du sein",
  chirurgieGynecologiqueEtObstetrique: "Chirurgie gynécologique et obstétrique",
  colposcopie: "Colposcopie",
  hysteroscopie: "Hystéroscopie",
  laserVaginal: "Laser vaginal",
  bouffeesDeChaleur: "Bouffées de chaleur",
  coelioscopie: "Coelioscopie",
  pilluleContraception: "Pillule  contraception",
  chirurgieGenerale: "Chirurgie générale",
  chirurgieHepatoBiliaire: "Chirurgie hépato-biliaire",
  hernieOmbilicaleOuVentrale: "Hernie ombilicale ou ventrale",
  hernieInguinale: "Hernie inguinale",
  grosVentreOuDiastasis: "Gros ventre ou diastasis",
  canalLombaireEtroit: "Canal lombaire étroit",
  chirurgieDeLaColonneVertebraleEtDeLaMoelleEpiniere:
    "Chirurgie de la colonne vertébrale et de la moelle épinière",
  chirurgieDeLaScoliose: "Chirurgie de la scoliose",
  hernieDiscale: "Hernie discale",
  sciatique: "Sciatique",
  spondylolisthesis: "Spondylolisthésis",
  chirurgieDuDos: "Chirurgie du dos",
  chirurgieDuDosEtDuRachis: "Chirurgie du dos et du rachis",
  grainsDeBeaute: "Grains de beauté",
  chirurgieCranienneEtCerebrale: "Chirurgie crânienne et cérébrale",
  neurochirurgieDuRachis: "Neurochirurgie du rachis",
  arteriographieCerebrale: "Artériographie cérébrale",
  tumeurCerebrale: "Tumeur cérébrale.",
  allergieCutanee: "Allergie cutanée",
  dermatologieChirurgicale: "Dermatologie chirurgicale",
  dermatologieEsthetique: "Dermatologie esthétique",
  dermatologieLaser: "Dermatologie laser",
  injections: "Injections",
  laser: "Laser",
  laserDermatologique: "Laser dermatologique",
  laserMedical: "Laser médical",
  laserVasculaire: "Laser vasculaire",
  pratiqueEsthetique: "Pratique esthétique",
  venerologie: "Vénérologie",
  acne: "Acné",
  dermatologieMedicale: "Dermatologie médicale",
  maladiesinfectionsSexuellementTransmissiblesMstist:
    "Maladies/infections sexuellement transmissibles (MST/IST)",
  peeling: "Peeling",
  cryotherapie: "Cryothérapie",
  dermatologiePediatrique: "Dermatologie pédiatrique",
  laserCo2: "Laser CO2",
  laserAblatif: "Laser ablatif",
  maladieDeVerneuilHidradeniteSuppuree:
    "Maladie de Verneuil (hidradénite suppurée)",
  mycose: "Mycose",
  melanome: "Mélanome",
  psoriasis: "psoriasis",
  rosacee: "Rosacée",
  verrue: "Verrue",
  infectionCutanee: "infection cutanée",
  angiome: "Angiome",
  couperose: "Couperose",
  dermiteSeborrheique: "Dermite séborrhéique",
  teigne: "Teigne",
  vitiligo: "Vitiligo",
  microneedling: "Microneedling",
  radiofrequence: "Radiofréquence",
  boutons: "Boutons",
  diabetologieDiabete: "Diabétologie diabéte",
  endocrinologieDiabetologie: "Endocrinologie diabétologie",
  adenomeHypophysaire: "Adénome hypophysaire",
  pompeAInsuline: "Pompe à insuline",
  medecineDeLaNutrition: "Médecine de la nutrition",
  diabeteGestationnel: "Diabète gestationnel",
  diabeteType1: "Diabète Type 1",
  diabeteType2: "Diabète Type 2",
  thyroide: "Thyroide",
  insuffisanceSurrenalienne: "Insuffisance surrénalienne",
  endoscopieDigestive: "Endoscopie digestive",
  gastroEnterologie: "Gastro-entérologie",
  proctologie: "Proctologie",
  proctologieMedicale: "Proctologie médicale",
  chirurgieDuReuxGastroSophagien: "Chirurgie du reﬂux gastro-œsophagien",
  reflux: "Reflux",
  troubleDuTransitConstipationDiarrhee:
    "Trouble du transit (constipation, diarrhée…)",
  chirurgieViscerale: "Chirurgie viscérale",
  troubleDigestif: "Trouble digestif",
  coloscopie: "Coloscopie",
  troubleDeLaDigestion: "Trouble de la digestion",
  ulcere: "Ulcère",
  vomissements: "Vomissements",
  hernieHiatale: "Hernie hiatale",
  fibroscopie: "Fibroscopie",
  anneauGastriqueBallonGastrique: "Anneau gastrique (ballon gastrique)",
  biologieGenetique: "Biologie génétique",
  bilanGenetique: "Bilan génétique",
  maladieHereditaire: "Maladie héréditaire",
  maladieGenetique: "Maladie génétique",
  gerontopsychiatrie: "Gérontopsychiatrie",
  maladieDeParkinson: "Maladie de Parkinson",
  maladieDalzheimer: "Maladie d'Alzheimer",
  bilanGeriatrique: "Bilan gériatrique",
  bilanLocomoteur: "Bilan locomoteur",
  gerontologie: "Gérontologie",
  alzheimer: "Alzheimer",
  holterEcg: "holter ecg",
  mapaHolterTensionnel: "mapa holter tensionnel",
  grossessePathologique: "Grossesse pathologique",
  gynecologieMedicale: "Gynécologie médicale",
  retraitDeSterilet: "Retrait de stérilet",
  echographiePelvienne: "Échographie pelvienne",
  gynecologieObstetrique: "Gynécologie obstétrique",
  echographieMammaire: "Échographie mammaire",
  echographieTransvaginale: "Echographie transvaginale",
  echographieDeStimulation: "Echographie de stimulation",
  contraceptionPilule: "Contraception  pilule",
  infertilite: "Infertilité",
  bilanBiologiqueDamylose: "Bilan biologique d'amylose",
  bilanDeCoagulation: "Bilan de coagulation",
  bilanDeBiologieHta: "Bilan de biologie HTA",
  bilanBiologiqueVascularite: "Bilan biologique vascularite",
  bilanDinsuffisanceCardiaque: "Bilan d'insuffisance cardiaque",
  bilanImmunologique: "Bilan immunologique",
  leucemie: "Leucémie",
  anemie: "Anémie",
  carenceEnFer: "Carence en fer",
  lymphome: "Lymphome",
  maladieDeBiermer: "Maladie de Biermer",
  bilanHypogammaglobuline: "Bilan Hypogammaglobuline",
  bilanDinsuffisanceRenale: "Bilan d'insuffisance rénale",
  bilanSanguinGeneralPriseDeSang: "Bilan sanguin général - prise de sang",
  maladiesDuSang: "Maladies du sang",
  maladieDeVaquez: "Maladie de Vaquez",
  purpuraThrombopeniqueImmunologiquePti:
    "Purpura Thrombopénique Immunologique (PTI)",
  immunologieEtHematologiePediatrique: "Immunologie et hématologie pédiatrique",
  electrophorese: "Electrophorèse",
  immunologie: "Immunologie",
  maladiesAutoImmunesEtInflammatoires:
    "Maladies auto-immunes et inflammatoires",
  immunodeficiencesAcquisesOuHereditaires:
    "Immunodéficiences (acquises ou héréditaires)",
  medecineDesMaladiesRares: "Médecine des maladies rares",
  immunotherapies: "Immunothérapies",
  hepatite: "Hépatite",
  medecineDesVoyages: "Médecine des voyages",
  prophylaxiePreExpositionPrep: "Prophylaxie pré-exposition (PrEP)",
  vih: "VIH",
  centreDeLutteAntiTuberculeuse: "Centre de lutte anti-tuberculeuse",
  medecineTropicale: "Médecine tropicale",
  medecineDeLenfantEtDeLadolescent: "Médecine de l'enfant et de l'adolescent",
  filsTenseurs: "Fils tenseurs",
  greffeCapillaire: "Greffe capillaire",
  cephaleeEtMigraine: "Céphalée et migraine",
  traumatologieDuSport: "Traumatologie du sport",
  vaccinationCovid19: "Vaccination COVID-19",
  medecineLegaleEtExpertisesMedicales:
    "Médecine légale et expertises médicales",
  medecinAgreePermisDeConduire: "Médecin agréé permis de conduire",
  laserEsthetique: "Laser esthétique",
  epilationLaser: "Epilation laser",
  sophrologie: "Sophrologie",
  calculsRenaux: "Calculs rénaux",
  dialyse: "Dialyse",
  hematurie: "Hématurie",
  insuffisanceRenale: "Insuffisance rénale",
  proteinurie: "Protéinurie",
  syndromeNephrotique: "Syndrome néphrotique",
  explorationRenale: "Exploration rénale",
  transplantationRenale: "Transplantation rénale",
  explorationNeurologique: "Exploration neurologique",
  electromyogrammeEmgDesMembresSuperieursEtInferieurs:
    "Électromyogramme (EMG) des membres supérieurs et inférieurs",
  scleroseEnPlaquesSep: "Sclérose en plaques (SEP)",
  electromyogrammeEmgDesMembresSuperieurs:
    "Electromyogramme (EMG) des membres supérieurs",
  electromyogrammeEmgDesMembresInferieurs:
    "Electromyogramme (EMG) des membres inférieurs",
  explorationFonctionnelleNeurologique:
    "Exploration fonctionnelle neurologique",
  examensNeurologiques: "Examens neurologiques",
  maladiesNeurodegeneratives: "Maladies neurodégénératives",
  maladiesDuCorpsDeLewy: "Maladies du corps de Lewy",
  reeducationNeuromotrice: "Rééducation neuromotrice",
  maladiesNeurologiquesRares: "Maladies neurologiques rares",
  avcAit: "AVC AIT",
  chimiotherapie: "Chimiothérapie.",
  cancerologieThoracique: "Cancérologie thoracique.",
  chirurgieRefractive: "Chirurgie réfractive",
  chirurgieOphtalmique: "Chirurgie ophtalmique",
  chirurgieDeLaMyopie: "Chirurgie de la myopie",
  chirurgieDeLaPresbytie: "Chirurgie de la presbytie",
  chirurgieDeLaCornee: "Chirurgie de la cornée",
  chirurgieDeLhypermetropie: "Chirurgie de l'hypermétropie",
  chirurgieDuGlaucome: "Chirurgie du glaucome",
  chirurgieDeLastigmatisme: "Chirurgie de l'astigmatisme",
  dmlaDegenerescenceMaculaireLieeeALage:
    "DMLA (Dégénerescence Maculaire Liéée à l'Age)",
  oct: "OCT",
  lasik: "LASIK",
  explorationOphtalmologique: "Exploration ophtalmologique",
  glaucome: "Glaucome",
  injectionIntravitreenne: "Injection intravitréenne",
  lentillesDeContact: "Lentilles de contact",
  presbylasik: "Presbylasik",
  bebeVision: "Bébé vision",
  suiviOphtalmologique: "Suivi ophtalmologique",
  medecineDuSurpoidsEtDeLobesitePediatrique:
    "Médecine du surpoids et de l'obésité pédiatrique",
  infectiologiePediatrique: "Infectiologie pédiatrique",
  neonatologie: "Néonatologie",
  troublesDuSommeil: "Troubles du sommeil",
  guidanceParentale: "Guidance parentale",
  allergologiePediatrique: "Allergologie pédiatrique",
  priseEnChargeDeLaDouleur: "Prise en charge de la douleur",
  allergieAlimentaire: "Allergie alimentaire",
  allergieAuxMedicaments: "Allergie aux médicaments",
  apneeDuSommeilDeLenfant: "Apnée du sommeil de l'enfant",
  insomnie: "Insomnie",
  medecineDuSommeil: "Médecine du sommeil",
  polygraphieNocturne: "Polygraphie nocturne",
  polysomnographie: "Polysomnographie",
  vaccination: "Vaccination",
  cancerDuPoumon: "cancer du poumon",
  bronchiteChroniqueBpco: "Bronchite chronique (BPCO)",
  bilanPneumologiqueEtRespiratoire: "Bilan pneumologique et respiratoire",
  gazDuSang: "Gaz du sang",
  testDuSommeilPolygraphiePolysmnographie:
    "Test du sommeil (polygraphie, polysmnographie)",
  essouflements: "Essouflements",
  therapieCognitiveEtComportementaleTcc:
    "Thérapie cognitive et comportementale (TCC)",
  burnOut: "Burn-out",
  psychiatriePolyvalente: "Psychiatrie polyvalente",
  troubleBipolaire: "Trouble bipolaire",
  diagnosticBipolarite: "Diagnostic bipolarité",
  diagnosticTdaTdah: "Diagnostic TDA / TDAH",
  testsPsychiques: "Tests psychiques",
  osteoporose: "Ostéoporose",
  rhumatismeInflammatoire: "Rhumatisme inflammatoire",
  tendinite: "Tendinite",
  echographieOsteoArticulaire: "Échographie ostéo-articulaire",
  polyarthrite: "Polyarthrite",
  spondylarthrite: "Spondylarthrite",
  viscosupplementation: "Viscosupplémentation",
  infiltrationEchoGuidee: "Infiltration écho-guidée",
  chirurgieBuccale: "Chirurgie buccale",
  chirurgieDermatologiqueCervicoFaciale:
    "Chirurgie dermatologique cervico-faciale",
  chirurgieDesDentsDeSagesse: "Chirurgie des dents de sagesse",
  chirurgieMaxilloFaciale: "Chirurgie maxillo-faciale",
  chirurgieOrthognathique: "Chirurgie orthognathique",
  chirurgiePreImplantaire: "Chirurgie pré-implantaire",
  implantologie: "Implantologie",
  implantologieDentaire: "Implantologie dentaire",
  stomatologie: "Stomatologie",
  bruxisme: "Bruxisme",
  greffeOsseuse: "Greffe osseuse",
  medecineDentaire: "Médecine dentaire",
  chirurgieDentaire: "Chirurgie dentaire",
  couronneDentaire: "Couronne dentaire",
  stelliteDentaire: "Stellite dentaire",
  dentisterieNumerique: "Dentisterie numérique",
  blanchimentDesDents: "Blanchiment des dents",
  extractionDentaire: "Extraction dentaire",
  carie: "Carie",
  echoDopplerDesTsa: "ÉCHO DOPPLER DES TSA",
  radioPanoramique: "Radio panoramique",
  radiographieDentaire: "Radiographie dentaire",
  coneBeam: "Cône beam",
  detartrage: "Détartrage",
  protheseDentaireFixeOuAmovible: "Prothèse dentaire fixe ou amovible",
  protheseSurImplant: "Prothèse sur implant",
  prophylaxie: "Prophylaxie",
  facetteDentaire: "Facette dentaire",
  orthodontiePourAdulte: "Orthodontie pour adulte",
  orthodontiePediatrique: "Orthodontie pédiatrique",
  orthopedieDentoFaciale: "Orthopédie dento-faciale",
  alignementDentaireInvisible: "Alignement dentaire invisible",
  appareilDentaire: "Appareil dentaire",
  dysfonctionnementTemporoMandibulaireDtm:
    "Dysfonctionnement temporo-mandibulaire (DTM)",
  gouttiereDentaire: "Gouttière dentaire",
  ortheseDavanceeMandibulaireOam: "Orthèse d'avancée mandibulaire (OAM)",
  techniqueLinguale: "Technique linguale",
  occlusodontie: "Occlusodontie",
  consultationOncologie: "consultation oncologie",
};

export const medicalExaminationMap: ObjectType = {
  Audiogramme: medicalExaminationsObj.audiogramme,
  Audiométrie: medicalExaminationsObj.audiometrie,
  Oncologie: medicalExaminationsObj.consultationOncologie,
  "echographie et doppler des troncs supra aortiques":
    medicalExaminationsObj.echoDopplerDesTsa,
  "echo-doppler pulse couleur des troncs supra-aortiques":
    medicalExaminationsObj.echoDopplerDesTsa,
  "Prothèse auditive": medicalExaminationsObj.protheseAuditive,
  Audiophonologie: medicalExaminationsObj.audiophonologie,
  Auriculothérapie: medicalExaminationsObj.auriculotherapie,
  Endométriose: medicalExaminationsObj.endometriose,
  "Médecine du surpoids et de l'obésité":
    medicalExaminationsObj.medecineDuSurpoidsEtDeLobesite,
  "Médecine Générale": medicalExaminationsObj.medecineGenerale,
  "Médecine préventive": medicalExaminationsObj.medecinePreventive,
  "Médecine traditionnelle chinoise (MTC)":
    medicalExaminationsObj.medecineTraditionnelleChinoiseMtc,
  Naturopathie: medicalExaminationsObj.naturopathie,
  Phytothérapie: medicalExaminationsObj.phytotherapie,
  "Sevrage tabagique": medicalExaminationsObj.sevrageTabagique,
  "Suivi de grossesse": medicalExaminationsObj.suiviDeGrossesse,
  "Évaluation et traitement de la douleur":
    medicalExaminationsObj.evaluationEtTraitementDeLaDouleur,
  Homéopathie: medicalExaminationsObj.homeopathie,
  Mésothérapie: medicalExaminationsObj.mesotherapie,
  Ostéopathie: medicalExaminationsObj.osteopathie,
  "Alimentation de la femme enceinte":
    medicalExaminationsObj.alimentationDeLaFemmeEnceinte,
  Allaitement: medicalExaminationsObj.allaitement,
  "Conseil en nutrition": medicalExaminationsObj.conseilEnNutrition,
  "Diététique pédiatrique": medicalExaminationsObj.dietetiquePediatrique,
  "Nutrition du sportif": medicalExaminationsObj.nutritionDuSportif,
  Obésité: medicalExaminationsObj.obesite,
  "Rééquilibrage alimentaire": medicalExaminationsObj.reequilibrageAlimentaire,
  "Soins de support oncologique":
    medicalExaminationsObj.soinsDeSupportOncologique,
  Surpoids: medicalExaminationsObj.surpoids,
  "Éducation au diabète": medicalExaminationsObj.educationAuDiabete,
  "Education thérapeutique": medicalExaminationsObj.educationTherapeutique,
  "Diététique énergétique": medicalExaminationsObj.dietetiqueEnergetique,
  "Drainage lymphatique": medicalExaminationsObj.drainageLymphatique,
  Luxopuncture: medicalExaminationsObj.luxopuncture,
  Micronutrition: medicalExaminationsObj.micronutrition,
  Nutrithérapie: medicalExaminationsObj.nutritherapie,
  "Conseil en diététique": medicalExaminationsObj.conseilEnDietetique,
  "Suivi du sportif": medicalExaminationsObj.suiviDuSportif,
  "Troubles du comportement alimentaire":
    medicalExaminationsObj.troublesDuComportementAlimentaire,
  "Accompagnement diététique post-chirurgie bariatrique":
    medicalExaminationsObj.accompagnementDietetiquePostChirurgieBariatrique,
  Nutrition: medicalExaminationsObj.nutrition,
  "Rééducation fonctionnelle": medicalExaminationsObj.reeducationFonctionnelle,
  "Auxiliaire médical en pratique avancée":
    medicalExaminationsObj.auxiliaireMedicalEnPratiqueAvancee,
  "Bilan cognitif": medicalExaminationsObj.bilanCognitif,
  "Bilan postural": medicalExaminationsObj.bilanPostural,
  "Rééducation des patients Alzheimer":
    medicalExaminationsObj.reeducationDesPatientsAlzheimer,
  "Rééducation neurologique": medicalExaminationsObj.reeducationNeurologique,
  "Conseil en aménagement du lieu de vie":
    medicalExaminationsObj.conseilEnAmenagementDuLieuDeVie,
  "Conseil en prévention des chutes":
    medicalExaminationsObj.conseilEnPreventionDesChutes,
  "Bilan psychomoteur": medicalExaminationsObj.bilanPsychomoteur,
  "Rééducation de l'écriture": medicalExaminationsObj.reeducationDeLecriture,
  Kinésithérapie: medicalExaminationsObj.kinesitherapie,
  "Kinésithérapie respiratoire et cardio-vasculaire":
    medicalExaminationsObj.kinesitherapieRespiratoireEtCardioVasculaire,
  "K-Tape": medicalExaminationsObj.kTape,
  Pressothérapie: medicalExaminationsObj.pressotherapie,
  "Traitement de la bronchiolite":
    medicalExaminationsObj.traitementDeLaBronchiolite,
  "Kinésithérapie du sport": medicalExaminationsObj.kinesitherapieDuSport,
  "Rééducation de l'épaule": medicalExaminationsObj.reeducationDeLepaule,
  "Rééducation du membre inférieur":
    medicalExaminationsObj.reeducationDuMembreInferieur,
  "Rééducation du genou": medicalExaminationsObj.reeducationDuGenou,
  "Rééducation de la cheville": medicalExaminationsObj.reeducationDeLaCheville,
  "Rééducation du pied": medicalExaminationsObj.reeducationDuPied,
  "Rééducation du dos": medicalExaminationsObj.reeducationDuDos,
  "Rééducation du bassin": medicalExaminationsObj.reeducationDuBassin,
  "Rééducation du membre supérieur":
    medicalExaminationsObj.reeducationDuMembreSuperieur,
  "Rééducation post-opératoire du ligament croisé antérieur":
    medicalExaminationsObj.reeducationPostOperatoireDuLigamentCroiseAnterieur,
  "Rééducation ora-faciale ou maxillo-faciale":
    medicalExaminationsObj.reeducationOraFacialeOuMaxilloFaciale,
  "Ostéopathie crânienne": medicalExaminationsObj.osteopathieCranienne,
  "Ostéopathie du sport": medicalExaminationsObj.osteopathieDuSport,
  "Ostéopathie maxillo-faciale et oro-faciale":
    medicalExaminationsObj.osteopathieMaxilloFacialeEtOroFaciale,
  "Ostéopathie myofasciale": medicalExaminationsObj.osteopathieMyofasciale,
  "Ostéopathie structurelle": medicalExaminationsObj.osteopathieStructurelle,
  "Ostéopathie viscérale": medicalExaminationsObj.osteopathieViscerale,
  "Ostéopathie de la femme": medicalExaminationsObj.osteopathieDeLaFemme,
  "Ostéopathie de la femme enceinte":
    medicalExaminationsObj.osteopathieDeLaFemmeEnceinte,
  "Ostéopathie pédiatrique": medicalExaminationsObj.osteopathiePediatrique,
  "Ostéopathie hémodynamique": medicalExaminationsObj.osteopathieHemodynamique,
  "Dépistage COVID-19 test PCR": medicalExaminationsObj.depistageCovid19TestPcr,
  "Dépistage COVID-19 test antigénique":
    medicalExaminationsObj.depistageCovid19TestAntigenique,
  Injection: medicalExaminationsObj.injection,
  "Vaccination (hors COVID-19)": medicalExaminationsObj.vaccinationHorsCovid19,
  Stomathérapie: medicalExaminationsObj.stomatherapie,
  "Traitement des cicatrices": medicalExaminationsObj.traitementDesCicatrices,
  "Vaccination antigrippale (Grippe)":
    medicalExaminationsObj.vaccinationAntigrippaleGrippe,
  "Bilan orthophonique": medicalExaminationsObj.bilanOrthophonique,
  "Rééducation orthophonique": medicalExaminationsObj.reeducationOrthophonique,
  "Rééducation de la déglutition":
    medicalExaminationsObj.reeducationDeLaDeglutition,
  "Rééducation oro-faciale": medicalExaminationsObj.reeducationOroFaciale,
  "Rééducation maxillo-faciale":
    medicalExaminationsObj.reeducationMaxilloFaciale,
  "Bilan orthoptique": medicalExaminationsObj.bilanOrthoptique,
  "Orthoptie pédiatrique": medicalExaminationsObj.orthoptiePediatrique,
  "Bilan de la vue": medicalExaminationsObj.bilanDeLaVue,
  Strabologie: medicalExaminationsObj.strabologie,
  Posturologie: medicalExaminationsObj.posturologie,
  "Champ visuel": medicalExaminationsObj.champVisuel,
  "Bilan et rééducation basse vision":
    medicalExaminationsObj.bilanEtReeducationBasseVision,
  "Bilan et rééducation neurovisuels":
    medicalExaminationsObj.bilanEtReeducationNeurovisuels,
  "Examens de la vision et des couleurs":
    medicalExaminationsObj.examensDeLaVisionEtDesCouleurs,
  "Bilan podologique": medicalExaminationsObj.bilanPodologique,
  Podologie: medicalExaminationsObj.podologie,
  "Podologie du sport": medicalExaminationsObj.podologieDuSport,
  Pédicurie: medicalExaminationsObj.pedicurie,
  "Semelles orthopédiques": medicalExaminationsObj.semellesOrthopediques,
  Orthoplastie: medicalExaminationsObj.orthoplastie,
  "Orthèse plantaire": medicalExaminationsObj.orthesePlantaire,
  "Thérapie psycho-corporelle": medicalExaminationsObj.therapiePsychoCorporelle,
  Addictologie: medicalExaminationsObj.addictologie,
  Périnatalité: medicalExaminationsObj.perinatalite,
  "Remédiation cognitive": medicalExaminationsObj.remediationCognitive,
  "Thérapie psycho-émotionnelle":
    medicalExaminationsObj.therapiePsychoEmotionnelle,
  "Accompagnement au développement personnel":
    medicalExaminationsObj.accompagnementAuDeveloppementPersonnel,
  "Approche psychosomatique": medicalExaminationsObj.approchePsychosomatique,
  "Gestion du stress": medicalExaminationsObj.gestionDuStress,
  "Psychologie clinique": medicalExaminationsObj.psychologieClinique,
  "Psychologie positive": medicalExaminationsObj.psychologiePositive,
  Psychotraumatologie: medicalExaminationsObj.psychotraumatologie,
  "Souffrance au travail": medicalExaminationsObj.souffranceAuTravail,
  "Thérapie analytique": medicalExaminationsObj.therapieAnalytique,
  "Thérapie d'orientation psychanalytique":
    medicalExaminationsObj.therapieDorientationPsychanalytique,
  "Thérapie troubles anxieux": medicalExaminationsObj.therapieTroublesAnxieux,
  Victimologie: medicalExaminationsObj.victimologie,
  "Accompagnement psychologique pour trouble de l'identité de genre":
    medicalExaminationsObj.accompagnementPsychologiquePourTroubleDeLidentiteDeGenre,
  Psychanalyse: medicalExaminationsObj.psychanalyse,
  "Psychologie de l'adulte": medicalExaminationsObj.psychologieDeLadulte,
  Psychothérapie: medicalExaminationsObj.psychotherapie,
  "Thérapie EMDR": medicalExaminationsObj.therapieEmdr,
  "Test de QI (Quotient Intellectuel)":
    medicalExaminationsObj.testDeQiQuotientIntellectuel,
  Contraception: medicalExaminationsObj.contraception,
  Frottis: medicalExaminationsObj.frottis,
  "Implant contraceptif": medicalExaminationsObj.implantContraceptif,
  Maternité: medicalExaminationsObj.maternite,
  "Pilule contraceptive": medicalExaminationsObj.piluleContraceptive,
  "Pose de stérilet": medicalExaminationsObj.poseDeSterilet,
  "Préparation à la naissance": medicalExaminationsObj.preparationALaNaissance,
  "Suivi en gynécologie": medicalExaminationsObj.suiviEnGynecologie,
  "Vaccination HPV (Papillomavirus)":
    medicalExaminationsObj.vaccinationHpvPapillomavirus,
  "Dépistage de papillomavirus humain (HPV)":
    medicalExaminationsObj.depistageDePapillomavirusHumainHpv,
  "Sage-femme": medicalExaminationsObj.sageFemme,
  "Interruption volontaire de grossesse (IVG) médicamenteuse":
    medicalExaminationsObj.interruptionVolontaireDeGrossesseIvgMedicamenteuse,
  "Planning familial": medicalExaminationsObj.planningFamilial,
  Echographie: medicalExaminationsObj.echographie,
  Echographiste: medicalExaminationsObj.echographiste,
  "Échographie de datation": medicalExaminationsObj.echographieDeDatation,
  "Echographie gynécologique et obstétricale":
    medicalExaminationsObj.echographieGynecologiqueEtObstetricale,
  "Échographie obstétricale": medicalExaminationsObj.echographieObstetricale,
  "Accouchement physiologique":
    medicalExaminationsObj.accouchementPhysiologique,
  Acupuncture: medicalExaminationsObj.acupuncture,
  Ménopause: medicalExaminationsObj.menopause,
  "PMA/AMP - FIV - Fertilité": medicalExaminationsObj.pmaampFivFertilite,
  Allergie: medicalExaminationsObj.allergie,
  "Allergie pollens": medicalExaminationsObj.allergiePollens,
  "Allergie respiratoire": medicalExaminationsObj.allergieRespiratoire,
  Allergologie: medicalExaminationsObj.allergologie,
  Artérite: medicalExaminationsObj.arterite,
  Doppler: medicalExaminationsObj.doppler,
  "Médecine vasculaire": medicalExaminationsObj.medecineVasculaire,
  Phlébologie: medicalExaminationsObj.phlebologie,
  "Sclérothérapie des varices": medicalExaminationsObj.sclerotherapieDesVarices,
  "Échodoppler vasculaire": medicalExaminationsObj.echodopplerVasculaire,
  Phlébite: medicalExaminationsObj.phlebite,
  Varices: medicalExaminationsObj.varices,
  "Ulcère des jambes": medicalExaminationsObj.ulcereDesJambes,
  Artériopathie: medicalExaminationsObj.arteriopathie,
  "Insuffisance cardiaque": medicalExaminationsObj.insuffisanceCardiaque,
  "Trouble du rythme": medicalExaminationsObj.troubleDuRythme,
  "Hypertension artérielle": medicalExaminationsObj.hypertensionArterielle,
  "Epreuve d'effort": medicalExaminationsObj.epreuveDeffort,
  Coronarographie: medicalExaminationsObj.coronarographie,
  Rythmologue: medicalExaminationsObj.rythmologue,
  Palpitations: medicalExaminationsObj.palpitations,
  Malaise: medicalExaminationsObj.malaise,
  "Perte de connaissance": medicalExaminationsObj.perteDeConnaissance,
  "Examens cardiologiques": medicalExaminationsObj.examensCardiologiques,
  "Cardiologie du sport": medicalExaminationsObj.cardiologieDuSport,
  Extrasystole: medicalExaminationsObj.extrasystole,
  Stent: medicalExaminationsObj.stent,
  "Douleurs à la poitrine": medicalExaminationsObj.douleursALaPoitrine,
  "douleurs thoraciques": medicalExaminationsObj.douleursThoraciques,
  Essoufflement: medicalExaminationsObj.essoufflement,
  Dyspnée: medicalExaminationsObj.dyspnee,
  "Oedème des jambes": medicalExaminationsObj.oedemeDesJambes,
  "Oedème pulmonaire": medicalExaminationsObj.oedemePulmonaire,
  "Chirurgie de la thyroïde": medicalExaminationsObj.chirurgieDeLaThyroide,
  "Chirurgie des cancers avec technique coelioscopique et robotique":
    medicalExaminationsObj.chirurgieDesCancersAvecTechniqueCoelioscopiqueEtRobotique,
  "Chirurgie cancérologique": medicalExaminationsObj.chirurgieCancerologique,
  "Chirurgie de la paroi abdominale":
    medicalExaminationsObj.chirurgieDeLaParoiAbdominale,
  "Chirurgie des voies biliaires":
    medicalExaminationsObj.chirurgieDesVoiesBiliaires,
  "Chirurgie digestive": medicalExaminationsObj.chirurgieDigestive,
  "Chirurgie du foie": medicalExaminationsObj.chirurgieDuFoie,
  "Cancer de l'estomac": medicalExaminationsObj.cancerDeLestomac,
  "Chirurgie du rectum": medicalExaminationsObj.chirurgieDuRectum,
  "Chirurgie bariatrique": medicalExaminationsObj.chirurgieBariatrique,
  Hernie: medicalExaminationsObj.hernie,
  "Chirurgie de l'obésité": medicalExaminationsObj.chirurgieDeLobesite,
  "Chirurgie herniaire": medicalExaminationsObj.chirurgieHerniaire,
  "Lithiase biliare": medicalExaminationsObj.lithiaseBiliare,
  "Chirurgie pariétale": medicalExaminationsObj.chirurgieParietale,
  "Chirurgie proctologique": medicalExaminationsObj.chirurgieProctologique,
  Hémorroides: medicalExaminationsObj.hemorroides,
  "Cancer de la vessie": medicalExaminationsObj.cancerDeLaVessie,
  "Cancer de la prostate": medicalExaminationsObj.cancerDeLaProstate,
  "Cancer du rein": medicalExaminationsObj.cancerDuRein,
  "Cancérologie urologique": medicalExaminationsObj.cancerologieUrologique,
  "Chirurgie de la lithiase urinaire":
    medicalExaminationsObj.chirurgieDeLaLithiaseUrinaire,
  "Chirurgie de la prostate": medicalExaminationsObj.chirurgieDeLaProstate,
  "Chirurgie de l'incontinence urinaire":
    medicalExaminationsObj.chirurgieDeLincontinenceUrinaire,
  "Chirurgie pelvienne": medicalExaminationsObj.chirurgiePelvienne,
  "Exploration urodynamique": medicalExaminationsObj.explorationUrodynamique,
  "Prolapsus ou descente d'organe":
    medicalExaminationsObj.prolapsusOuDescenteDorgane,
  "Colique néphrétique   calculs rénaux":
    medicalExaminationsObj.coliqueNephretiqueCalculsRenaux,
  Prostate: medicalExaminationsObj.prostate,
  "Incontinence urinaire": medicalExaminationsObj.incontinenceUrinaire,
  "Difficultés à uriner": medicalExaminationsObj.difficultesAUriner,
  "Trouble de l'erection": medicalExaminationsObj.troubleDeLerection,
  "Sang dans les urines": medicalExaminationsObj.sangDansLesUrines,
  "Chirurgie de l'épaule": medicalExaminationsObj.chirurgieDeLepaule,
  "Chirurgie de la cheville": medicalExaminationsObj.chirurgieDeLaCheville,
  "Chirurgie de la hanche": medicalExaminationsObj.chirurgieDeLaHanche,
  "Chirurgie du genou": medicalExaminationsObj.chirurgieDuGenou,
  "Chirurgie de la main": medicalExaminationsObj.chirurgieDeLaMain,
  "Chirurgie du poignet": medicalExaminationsObj.chirurgieDuPoignet,
  "Chirurgie du coude": medicalExaminationsObj.chirurgieDuCoude,
  "Chirurgie des ligaments croisés":
    medicalExaminationsObj.chirurgieDesLigamentsCroises,
  Arthrose: medicalExaminationsObj.arthrose,
  "Arthroscopie du genou": medicalExaminationsObj.arthroscopieDuGenou,
  "Chirurgie arthroscopique": medicalExaminationsObj.chirurgieArthroscopique,
  Arthroscopie: medicalExaminationsObj.arthroscopie,
  Infiltration: medicalExaminationsObj.infiltration,
  "Canal carpien": medicalExaminationsObj.canalCarpien,
  Cervicalgie: medicalExaminationsObj.cervicalgie,
  Lombalgie: medicalExaminationsObj.lombalgie,
  "Médecine du sport": medicalExaminationsObj.medecineDuSport,
  "Névralgie cervico-brachiale":
    medicalExaminationsObj.nevralgieCervicoBrachiale,
  Orthopédie: medicalExaminationsObj.orthopedie,
  "Traumatologie pédiatrique": medicalExaminationsObj.traumatologiePediatrique,
  "Chirurgie du pied": medicalExaminationsObj.chirurgieDuPied,
  "Chirurgie du rachis": medicalExaminationsObj.chirurgieDuRachis,
  Fracture: medicalExaminationsObj.fracture,
  "Difficultés à la marche": medicalExaminationsObj.difficultesALaMarche,
  "Douleurs dorsales": medicalExaminationsObj.douleursDorsales,
  "Douleurs lombaires": medicalExaminationsObj.douleursLombaires,
  "Douleurs cervicales": medicalExaminationsObj.douleursCervicales,
  "Cancer de l'utérus": medicalExaminationsObj.cancerDeLuterus,
  "Cancérologie du sein.": medicalExaminationsObj.cancerologieDuSein,
  "Cancérologie gynécologique":
    medicalExaminationsObj.cancerologieGynecologique,
  "Chirurgie esthétique": medicalExaminationsObj.chirurgieEsthetique,
  "Chirurgie plastique": medicalExaminationsObj.chirurgiePlastique,
  "Médecine esthétique": medicalExaminationsObj.medecineEsthetique,
  "Body lift": medicalExaminationsObj.bodyLift,
  "Chirurgie dermatologique": medicalExaminationsObj.chirurgieDermatologique,
  "Chirurgie plastique et esthétique de la face et du cou":
    medicalExaminationsObj.chirurgiePlastiqueEtEsthetiqueDeLaFaceEtDuCou,
  "Chirurgie du visage": medicalExaminationsObj.chirurgieDuVisage,
  "Chirurgie esthétique et réparation du sein":
    medicalExaminationsObj.chirurgieEsthetiqueEtReparationDuSein,
  Botox: medicalExaminationsObj.botox,
  Lifting: medicalExaminationsObj.lifting,
  "Chirurgie thoracique et cardio-vasculaire":
    medicalExaminationsObj.chirurgieThoraciqueEtCardioVasculaire,
  "Chirurgie cardiaque": medicalExaminationsObj.chirurgieCardiaque,
  "Dissection aortique": medicalExaminationsObj.dissectionAortique,
  Pontage: medicalExaminationsObj.pontage,
  "Chirurgie valvulaire": medicalExaminationsObj.chirurgieValvulaire,
  "Chirurgie cardiaque pédiatrique":
    medicalExaminationsObj.chirurgieCardiaquePediatrique,
  "Chirurgie vasculaire": medicalExaminationsObj.chirurgieVasculaire,
  Angiographie: medicalExaminationsObj.angiographie,
  "Chirurgie de la cataracte": medicalExaminationsObj.chirurgieDeLaCataracte,
  "Chirurgie de la rétine": medicalExaminationsObj.chirurgieDeLaRetine,
  "Chirurgie ophtalmologique": medicalExaminationsObj.chirurgieOphtalmologique,
  "Chirurgie de la réfraction": medicalExaminationsObj.chirurgieDeLaRefraction,
  "Chirurgien des paupières": medicalExaminationsObj.chirurgienDesPaupieres,
  Cataracte: medicalExaminationsObj.cataracte,
  "Chirurgie des paupières": medicalExaminationsObj.chirurgieDesPaupieres,
  "Chirurgie Laser": medicalExaminationsObj.chirurgieLaser,
  "Chirurgie des voies lacrymales":
    medicalExaminationsObj.chirurgieDesVoiesLacrymales,
  "Chirurgie oculoplastique": medicalExaminationsObj.chirurgieOculoplastique,
  "Douleurs aux yeux": medicalExaminationsObj.douleursAuxYeux,
  "Baisse de la vue": medicalExaminationsObj.baisseDeLaVue,
  "Infections à l'œil": medicalExaminationsObj.infectionsALil,
  Conjonctivite: medicalExaminationsObj.conjonctivite,
  "Perte de la vue": medicalExaminationsObj.perteDeLaVue,
  "Paupières enflées": medicalExaminationsObj.paupieresEnflees,
  "Chirurgie des glandes salivaires":
    medicalExaminationsObj.chirurgieDesGlandesSalivaires,
  "Chirurgie des sinus": medicalExaminationsObj.chirurgieDesSinus,
  "Chirurgie des tumeurs cutanées de la face et du cou":
    medicalExaminationsObj.chirurgieDesTumeursCutaneesDeLaFaceEtDuCou,
  "Chirurgie endonasale": medicalExaminationsObj.chirurgieEndonasale,
  "Chirurgie orale": medicalExaminationsObj.chirurgieOrale,
  "ORL cancérologique.": medicalExaminationsObj.orlCancerologique,
  "ORL rhinologique": medicalExaminationsObj.orlRhinologique,
  "Oto-rhino-laryngologie": medicalExaminationsObj.otoRhinoLaryngologie,
  Otospongiose: medicalExaminationsObj.otospongiose,
  "Polygraphie ventilatoire": medicalExaminationsObj.polygraphieVentilatoire,
  "Rhinoplastie chirurgicale": medicalExaminationsObj.rhinoplastieChirurgicale,
  Ronflements: medicalExaminationsObj.ronflements,
  Tympanoplastie: medicalExaminationsObj.tympanoplastie,
  Acouphènes: medicalExaminationsObj.acouphenes,
  "Apnée du sommeil": medicalExaminationsObj.apneeDuSommeil,
  "Chirurgie de l'oreille": medicalExaminationsObj.chirurgieDeLoreille,
  "Chirurgie de la face et du cou":
    medicalExaminationsObj.chirurgieDeLaFaceEtDuCou,
  Endoscopie: medicalExaminationsObj.endoscopie,
  "ORL et chirurgie cervico-faciale":
    medicalExaminationsObj.orlEtChirurgieCervicoFaciale,
  Otite: medicalExaminationsObj.otite,
  "Mal aux oreilles": medicalExaminationsObj.malAuxOreilles,
  "ORL gériatrique": medicalExaminationsObj.orlGeriatrique,
  "ORL pédiatrique": medicalExaminationsObj.orlPediatrique,
  "Perte de l'audition": medicalExaminationsObj.perteDeLaudition,
  "Bouchon d'oreille": medicalExaminationsObj.bouchonDoreille,
  "Chirurgie artérielle et veineuse":
    medicalExaminationsObj.chirurgieArterielleEtVeineuse,
  "Chirurgie des varices": medicalExaminationsObj.chirurgieDesVarices,
  "Chirurgie endovasculaire": medicalExaminationsObj.chirurgieEndovasculaire,
  "Ulcère de jambe": medicalExaminationsObj.ulcereDeJambe,
  Artériographie: medicalExaminationsObj.arteriographie,
  "Chirurgie gynécologique": medicalExaminationsObj.chirurgieGynecologique,
  "Chirurgie sénologie": medicalExaminationsObj.chirurgieSenologie,
  "Fibrome utérin": medicalExaminationsObj.fibromeUterin,
  "Gynécologie médicale et obstétrique":
    medicalExaminationsObj.gynecologieMedicaleEtObstetrique,
  Gynécologue: medicalExaminationsObj.gynecologue,
  "Augmentation mammaire": medicalExaminationsObj.augmentationMammaire,
  "Chirurgie mammaire": medicalExaminationsObj.chirurgieMammaire,
  "Implant mammaire": medicalExaminationsObj.implantMammaire,
  "Injection d'acide hyaluronique":
    medicalExaminationsObj.injectionDacideHyaluronique,
  "Injection de toxine botulique":
    medicalExaminationsObj.injectionDeToxineBotulique,
  "Lifting mammaire": medicalExaminationsObj.liftingMammaire,
  Lipoaspiration: medicalExaminationsObj.lipoaspiration,
  "Lipofilling mammaire": medicalExaminationsObj.lipofillingMammaire,
  Otoplastie: medicalExaminationsObj.otoplastie,
  "Plastie abdominale": medicalExaminationsObj.plastieAbdominale,
  "Plastie mammaire": medicalExaminationsObj.plastieMammaire,
  "Réduction mammaire": medicalExaminationsObj.reductionMammaire,
  Liposuccion: medicalExaminationsObj.liposuccion,
  "Changement de prothèses mammaires":
    medicalExaminationsObj.changementDeProthesesMammaires,
  "Prothèses de mollet": medicalExaminationsObj.prothesesDeMollet,
  "Blépharoplastie (chirurgie des paupières)":
    medicalExaminationsObj.blepharoplastieChirurgieDesPaupieres,
  "Oreilles décollées": medicalExaminationsObj.oreillesDecollees,
  "Abdominoplastie (chirurgie du ventre)":
    medicalExaminationsObj.abdominoplastieChirurgieDuVentre,
  "Augmentation mammaire par lipofilling (graisse)":
    medicalExaminationsObj.augmentationMammaireParLipofillingGraisse,
  "Chirurgie de la stérilité": medicalExaminationsObj.chirurgieDeLaSterilite,
  "Chirurgie du sein": medicalExaminationsObj.chirurgieDuSein,
  "Chirurgie gynécologique et obstétrique":
    medicalExaminationsObj.chirurgieGynecologiqueEtObstetrique,
  Colposcopie: medicalExaminationsObj.colposcopie,
  Hystéroscopie: medicalExaminationsObj.hysteroscopie,
  "Laser vaginal": medicalExaminationsObj.laserVaginal,
  "Bouffées de chaleur": medicalExaminationsObj.bouffeesDeChaleur,
  Coelioscopie: medicalExaminationsObj.coelioscopie,
  "Pillule  contraception": medicalExaminationsObj.pilluleContraception,
  "Chirurgie générale": medicalExaminationsObj.chirurgieGenerale,
  "Chirurgie hépato-biliaire": medicalExaminationsObj.chirurgieHepatoBiliaire,
  "Hernie ombilicale ou ventrale":
    medicalExaminationsObj.hernieOmbilicaleOuVentrale,
  "Hernie inguinale": medicalExaminationsObj.hernieInguinale,
  "Gros ventre ou diastasis": medicalExaminationsObj.grosVentreOuDiastasis,
  "Canal lombaire étroit": medicalExaminationsObj.canalLombaireEtroit,
  "Chirurgie de la colonne vertébrale et de la moelle épinière":
    medicalExaminationsObj.chirurgieDeLaColonneVertebraleEtDeLaMoelleEpiniere,
  "Chirurgie de la scoliose": medicalExaminationsObj.chirurgieDeLaScoliose,
  "Hernie discale": medicalExaminationsObj.hernieDiscale,
  Sciatique: medicalExaminationsObj.sciatique,
  Spondylolisthésis: medicalExaminationsObj.spondylolisthesis,
  "Chirurgie du dos": medicalExaminationsObj.chirurgieDuDos,
  "Chirurgie du dos et du rachis":
    medicalExaminationsObj.chirurgieDuDosEtDuRachis,
  "Grains de beauté": medicalExaminationsObj.grainsDeBeaute,
  "Chirurgie crânienne et cérébrale":
    medicalExaminationsObj.chirurgieCranienneEtCerebrale,
  "Neurochirurgie du rachis": medicalExaminationsObj.neurochirurgieDuRachis,
  "Artériographie cérébrale": medicalExaminationsObj.arteriographieCerebrale,
  "Tumeur cérébrale.": medicalExaminationsObj.tumeurCerebrale,
  "Allergie cutanée": medicalExaminationsObj.allergieCutanee,
  "Dermatologie chirurgicale": medicalExaminationsObj.dermatologieChirurgicale,
  "Dermatologie esthétique": medicalExaminationsObj.dermatologieEsthetique,
  "Dermatologie laser": medicalExaminationsObj.dermatologieLaser,
  Injections: medicalExaminationsObj.injections,
  Laser: medicalExaminationsObj.laser,
  "Laser dermatologique": medicalExaminationsObj.laserDermatologique,
  "Laser médical": medicalExaminationsObj.laserMedical,
  "Laser vasculaire": medicalExaminationsObj.laserVasculaire,
  "Pratique esthétique": medicalExaminationsObj.pratiqueEsthetique,
  Vénérologie: medicalExaminationsObj.venerologie,
  Acné: medicalExaminationsObj.acne,
  "Dermatologie médicale": medicalExaminationsObj.dermatologieMedicale,
  "Maladies/infections sexuellement transmissibles (MST/IST)":
    medicalExaminationsObj.maladiesinfectionsSexuellementTransmissiblesMstist,
  Peeling: medicalExaminationsObj.peeling,
  Cryothérapie: medicalExaminationsObj.cryotherapie,
  "Dermatologie pédiatrique": medicalExaminationsObj.dermatologiePediatrique,
  "Laser CO2": medicalExaminationsObj.laserCo2,
  "Laser ablatif": medicalExaminationsObj.laserAblatif,
  "Maladie de Verneuil (hidradénite suppurée)":
    medicalExaminationsObj.maladieDeVerneuilHidradeniteSuppuree,
  Mycose: medicalExaminationsObj.mycose,
  Mélanome: medicalExaminationsObj.melanome,
  psoriasis: medicalExaminationsObj.psoriasis,
  Rosacée: medicalExaminationsObj.rosacee,
  Verrue: medicalExaminationsObj.verrue,
  "infection cutanée": medicalExaminationsObj.infectionCutanee,
  Angiome: medicalExaminationsObj.angiome,
  Couperose: medicalExaminationsObj.couperose,
  "Dermite séborrhéique": medicalExaminationsObj.dermiteSeborrheique,
  Teigne: medicalExaminationsObj.teigne,
  Vitiligo: medicalExaminationsObj.vitiligo,
  Microneedling: medicalExaminationsObj.microneedling,
  Radiofréquence: medicalExaminationsObj.radiofrequence,
  Boutons: medicalExaminationsObj.boutons,
  "Diabétologie diabéte": medicalExaminationsObj.diabetologieDiabete,
  "Endocrinologie diabétologie":
    medicalExaminationsObj.endocrinologieDiabetologie,
  "Adénome hypophysaire": medicalExaminationsObj.adenomeHypophysaire,
  "Pompe à insuline": medicalExaminationsObj.pompeAInsuline,
  "Médecine de la nutrition": medicalExaminationsObj.medecineDeLaNutrition,
  "Diabète gestationnel": medicalExaminationsObj.diabeteGestationnel,
  "Diabète Type 1": medicalExaminationsObj.diabeteType1,
  "Diabète Type 2": medicalExaminationsObj.diabeteType2,
  Thyroide: medicalExaminationsObj.thyroide,
  "Insuffisance surrénalienne":
    medicalExaminationsObj.insuffisanceSurrenalienne,
  "Endoscopie digestive": medicalExaminationsObj.endoscopieDigestive,
  "Gastro-entérologie": medicalExaminationsObj.gastroEnterologie,
  Proctologie: medicalExaminationsObj.proctologie,
  "Proctologie médicale": medicalExaminationsObj.proctologieMedicale,
  "Chirurgie du reﬂux gastro-œsophagien":
    medicalExaminationsObj.chirurgieDuReuxGastroSophagien,
  Reflux: medicalExaminationsObj.reflux,
  "Trouble du transit (constipation, diarrhée…)":
    medicalExaminationsObj.troubleDuTransitConstipationDiarrhee,
  "Chirurgie viscérale": medicalExaminationsObj.chirurgieViscerale,
  "Trouble digestif": medicalExaminationsObj.troubleDigestif,
  Coloscopie: medicalExaminationsObj.coloscopie,
  "Trouble de la digestion": medicalExaminationsObj.troubleDeLaDigestion,
  Ulcère: medicalExaminationsObj.ulcere,
  Vomissements: medicalExaminationsObj.vomissements,
  "Hernie hiatale": medicalExaminationsObj.hernieHiatale,
  Fibroscopie: medicalExaminationsObj.fibroscopie,
  "Anneau gastrique (ballon gastrique)":
    medicalExaminationsObj.anneauGastriqueBallonGastrique,
  "Biologie génétique": medicalExaminationsObj.biologieGenetique,
  "Bilan génétique": medicalExaminationsObj.bilanGenetique,
  "Maladie héréditaire": medicalExaminationsObj.maladieHereditaire,
  "Maladie génétique": medicalExaminationsObj.maladieGenetique,
  Gérontopsychiatrie: medicalExaminationsObj.gerontopsychiatrie,
  "Maladie de Parkinson": medicalExaminationsObj.maladieDeParkinson,
  "Maladie d'Alzheimer": medicalExaminationsObj.maladieDalzheimer,
  "Bilan gériatrique": medicalExaminationsObj.bilanGeriatrique,
  "Bilan locomoteur": medicalExaminationsObj.bilanLocomoteur,
  Gérontologie: medicalExaminationsObj.gerontologie,
  Alzheimer: medicalExaminationsObj.alzheimer,
  "holter ecg": medicalExaminationsObj.holterEcg,
  "mapa holter tensionnel": medicalExaminationsObj.mapaHolterTensionnel,
  "Grossesse pathologique": medicalExaminationsObj.grossessePathologique,
  "Gynécologie médicale": medicalExaminationsObj.gynecologieMedicale,
  "Retrait de stérilet": medicalExaminationsObj.retraitDeSterilet,
  "Échographie pelvienne": medicalExaminationsObj.echographiePelvienne,
  "Gynécologie obstétrique": medicalExaminationsObj.gynecologieObstetrique,
  "Échographie mammaire": medicalExaminationsObj.echographieMammaire,
  "Echographie transvaginale": medicalExaminationsObj.echographieTransvaginale,
  "Echographie de stimulation": medicalExaminationsObj.echographieDeStimulation,
  "Contraception  pilule": medicalExaminationsObj.contraceptionPilule,
  Infertilité: medicalExaminationsObj.infertilite,
  "Bilan biologique d'amylose": medicalExaminationsObj.bilanBiologiqueDamylose,
  "Bilan de coagulation": medicalExaminationsObj.bilanDeCoagulation,
  "Bilan de biologie HTA": medicalExaminationsObj.bilanDeBiologieHta,
  "Bilan biologique vascularite":
    medicalExaminationsObj.bilanBiologiqueVascularite,
  "Bilan d'insuffisance cardiaque":
    medicalExaminationsObj.bilanDinsuffisanceCardiaque,
  "Bilan immunologique": medicalExaminationsObj.bilanImmunologique,
  Leucémie: medicalExaminationsObj.leucemie,
  Anémie: medicalExaminationsObj.anemie,
  "Carence en fer": medicalExaminationsObj.carenceEnFer,
  Lymphome: medicalExaminationsObj.lymphome,
  "Maladie de Biermer": medicalExaminationsObj.maladieDeBiermer,
  "Bilan Hypogammaglobuline": medicalExaminationsObj.bilanHypogammaglobuline,
  "Bilan d'insuffisance rénale":
    medicalExaminationsObj.bilanDinsuffisanceRenale,
  "Bilan sanguin général - prise de sang":
    medicalExaminationsObj.bilanSanguinGeneralPriseDeSang,
  "Maladies du sang": medicalExaminationsObj.maladiesDuSang,
  "Maladie de Vaquez": medicalExaminationsObj.maladieDeVaquez,
  "Purpura Thrombopénique Immunologique (PTI)":
    medicalExaminationsObj.purpuraThrombopeniqueImmunologiquePti,
  "Immunologie et hématologie pédiatrique":
    medicalExaminationsObj.immunologieEtHematologiePediatrique,
  Electrophorèse: medicalExaminationsObj.electrophorese,
  Immunologie: medicalExaminationsObj.immunologie,
  "Maladies auto-immunes et inflammatoires":
    medicalExaminationsObj.maladiesAutoImmunesEtInflammatoires,
  "Immunodéficiences (acquises ou héréditaires)":
    medicalExaminationsObj.immunodeficiencesAcquisesOuHereditaires,
  "Médecine des maladies rares":
    medicalExaminationsObj.medecineDesMaladiesRares,
  Immunothérapies: medicalExaminationsObj.immunotherapies,
  Hépatite: medicalExaminationsObj.hepatite,
  "Médecine des voyages": medicalExaminationsObj.medecineDesVoyages,
  "Prophylaxie pré-exposition (PrEP)":
    medicalExaminationsObj.prophylaxiePreExpositionPrep,
  VIH: medicalExaminationsObj.vih,
  "Centre de lutte anti-tuberculeuse":
    medicalExaminationsObj.centreDeLutteAntiTuberculeuse,
  "Médecine tropicale": medicalExaminationsObj.medecineTropicale,
  "Médecine de l'enfant et de l'adolescent":
    medicalExaminationsObj.medecineDeLenfantEtDeLadolescent,
  "Fils tenseurs": medicalExaminationsObj.filsTenseurs,
  "Greffe capillaire": medicalExaminationsObj.greffeCapillaire,
  "Céphalée et migraine": medicalExaminationsObj.cephaleeEtMigraine,
  "Traumatologie du sport": medicalExaminationsObj.traumatologieDuSport,
  "Vaccination COVID-19": medicalExaminationsObj.vaccinationCovid19,
  "Médecine légale et expertises médicales":
    medicalExaminationsObj.medecineLegaleEtExpertisesMedicales,
  "Médecin agréé permis de conduire":
    medicalExaminationsObj.medecinAgreePermisDeConduire,
  "Laser esthétique": medicalExaminationsObj.laserEsthetique,
  "Epilation laser": medicalExaminationsObj.epilationLaser,
  Sophrologie: medicalExaminationsObj.sophrologie,
  "Calculs rénaux": medicalExaminationsObj.calculsRenaux,
  Dialyse: medicalExaminationsObj.dialyse,
  Hématurie: medicalExaminationsObj.hematurie,
  "Insuffisance rénale": medicalExaminationsObj.insuffisanceRenale,
  Protéinurie: medicalExaminationsObj.proteinurie,
  "Syndrome néphrotique": medicalExaminationsObj.syndromeNephrotique,
  "Exploration rénale": medicalExaminationsObj.explorationRenale,
  "Transplantation rénale": medicalExaminationsObj.transplantationRenale,
  "Exploration neurologique": medicalExaminationsObj.explorationNeurologique,
  "Électromyogramme (EMG) des membres supérieurs et inférieurs":
    medicalExaminationsObj.electromyogrammeEmgDesMembresSuperieursEtInferieurs,
  "Sclérose en plaques (SEP)": medicalExaminationsObj.scleroseEnPlaquesSep,
  "Electromyogramme (EMG) des membres supérieurs":
    medicalExaminationsObj.electromyogrammeEmgDesMembresSuperieurs,
  "Electromyogramme (EMG) des membres inférieurs":
    medicalExaminationsObj.electromyogrammeEmgDesMembresInferieurs,
  "Exploration fonctionnelle neurologique":
    medicalExaminationsObj.explorationFonctionnelleNeurologique,
  "Examens neurologiques": medicalExaminationsObj.examensNeurologiques,
  "Maladies neurodégénératives":
    medicalExaminationsObj.maladiesNeurodegeneratives,
  "Maladies du corps de Lewy": medicalExaminationsObj.maladiesDuCorpsDeLewy,
  "Rééducation neuromotrice": medicalExaminationsObj.reeducationNeuromotrice,
  "Maladies neurologiques rares":
    medicalExaminationsObj.maladiesNeurologiquesRares,
  "AVC AIT": medicalExaminationsObj.avcAit,
  "Chimiothérapie.": medicalExaminationsObj.chimiotherapie,
  "Cancérologie thoracique.": medicalExaminationsObj.cancerologieThoracique,
  "Chirurgie réfractive": medicalExaminationsObj.chirurgieRefractive,
  "Chirurgie ophtalmique": medicalExaminationsObj.chirurgieOphtalmique,
  "Chirurgie de la myopie": medicalExaminationsObj.chirurgieDeLaMyopie,
  "Chirurgie de la presbytie": medicalExaminationsObj.chirurgieDeLaPresbytie,
  "Chirurgie de la cornée": medicalExaminationsObj.chirurgieDeLaCornee,
  "Chirurgie de l'hypermétropie":
    medicalExaminationsObj.chirurgieDeLhypermetropie,
  "Chirurgie du glaucome": medicalExaminationsObj.chirurgieDuGlaucome,
  "Chirurgie de l'astigmatisme":
    medicalExaminationsObj.chirurgieDeLastigmatisme,
  "DMLA (Dégénerescence Maculaire Liéée à l'Age)":
    medicalExaminationsObj.dmlaDegenerescenceMaculaireLieeeALage,
  OCT: medicalExaminationsObj.oct,
  LASIK: medicalExaminationsObj.lasik,
  "Exploration ophtalmologique":
    medicalExaminationsObj.explorationOphtalmologique,
  Glaucome: medicalExaminationsObj.glaucome,
  "Injection intravitréenne": medicalExaminationsObj.injectionIntravitreenne,
  "Lentilles de contact": medicalExaminationsObj.lentillesDeContact,
  Presbylasik: medicalExaminationsObj.presbylasik,
  "Bébé vision": medicalExaminationsObj.bebeVision,
  "Suivi ophtalmologique": medicalExaminationsObj.suiviOphtalmologique,
  "Médecine du surpoids et de l'obésité pédiatrique":
    medicalExaminationsObj.medecineDuSurpoidsEtDeLobesitePediatrique,
  "Infectiologie pédiatrique": medicalExaminationsObj.infectiologiePediatrique,
  Néonatologie: medicalExaminationsObj.neonatologie,
  "Troubles du sommeil": medicalExaminationsObj.troublesDuSommeil,
  "Guidance parentale": medicalExaminationsObj.guidanceParentale,
  "Allergologie pédiatrique": medicalExaminationsObj.allergologiePediatrique,
  "Prise en charge de la douleur":
    medicalExaminationsObj.priseEnChargeDeLaDouleur,
  "Allergie alimentaire": medicalExaminationsObj.allergieAlimentaire,
  "Allergie aux médicaments": medicalExaminationsObj.allergieAuxMedicaments,
  "Apnée du sommeil de l'enfant":
    medicalExaminationsObj.apneeDuSommeilDeLenfant,
  Insomnie: medicalExaminationsObj.insomnie,
  "Médecine du sommeil": medicalExaminationsObj.medecineDuSommeil,
  "Polygraphie nocturne": medicalExaminationsObj.polygraphieNocturne,
  Polysomnographie: medicalExaminationsObj.polysomnographie,
  Vaccination: medicalExaminationsObj.vaccination,
  "cancer du poumon": medicalExaminationsObj.cancerDuPoumon,
  "Bronchite chronique (BPCO)": medicalExaminationsObj.bronchiteChroniqueBpco,
  "Bilan pneumologique et respiratoire":
    medicalExaminationsObj.bilanPneumologiqueEtRespiratoire,
  "Gaz du sang": medicalExaminationsObj.gazDuSang,
  "Test du sommeil (polygraphie, polysmnographie)":
    medicalExaminationsObj.testDuSommeilPolygraphiePolysmnographie,
  Essouflements: medicalExaminationsObj.essouflements,
  "Thérapie cognitive et comportementale (TCC)":
    medicalExaminationsObj.therapieCognitiveEtComportementaleTcc,
  "Burn-out": medicalExaminationsObj.burnOut,
  "Psychiatrie polyvalente": medicalExaminationsObj.psychiatriePolyvalente,
  "Trouble bipolaire": medicalExaminationsObj.troubleBipolaire,
  "Diagnostic bipolarité": medicalExaminationsObj.diagnosticBipolarite,
  "Diagnostic TDA / TDAH": medicalExaminationsObj.diagnosticTdaTdah,
  "Tests psychiques": medicalExaminationsObj.testsPsychiques,
  Ostéoporose: medicalExaminationsObj.osteoporose,
  "Rhumatisme inflammatoire": medicalExaminationsObj.rhumatismeInflammatoire,
  Tendinite: medicalExaminationsObj.tendinite,
  "Échographie ostéo-articulaire":
    medicalExaminationsObj.echographieOsteoArticulaire,
  Polyarthrite: medicalExaminationsObj.polyarthrite,
  Spondylarthrite: medicalExaminationsObj.spondylarthrite,
  Viscosupplémentation: medicalExaminationsObj.viscosupplementation,
  "Infiltration écho-guidée": medicalExaminationsObj.infiltrationEchoGuidee,
  "Chirurgie buccale": medicalExaminationsObj.chirurgieBuccale,
  "Chirurgie dermatologique cervico-faciale":
    medicalExaminationsObj.chirurgieDermatologiqueCervicoFaciale,
  "Chirurgie des dents de sagesse":
    medicalExaminationsObj.chirurgieDesDentsDeSagesse,
  "Chirurgie maxillo-faciale": medicalExaminationsObj.chirurgieMaxilloFaciale,
  "Chirurgie orthognathique": medicalExaminationsObj.chirurgieOrthognathique,
  "Chirurgie pré-implantaire": medicalExaminationsObj.chirurgiePreImplantaire,
  Implantologie: medicalExaminationsObj.implantologie,
  "Implantologie dentaire": medicalExaminationsObj.implantologieDentaire,
  Stomatologie: medicalExaminationsObj.stomatologie,
  Bruxisme: medicalExaminationsObj.bruxisme,
  "Greffe osseuse": medicalExaminationsObj.greffeOsseuse,
  "Médecine dentaire": medicalExaminationsObj.medecineDentaire,
  "Chirurgie dentaire": medicalExaminationsObj.chirurgieDentaire,
  "Couronne dentaire": medicalExaminationsObj.couronneDentaire,
  "Stellite dentaire": medicalExaminationsObj.stelliteDentaire,
  "Dentisterie numérique": medicalExaminationsObj.dentisterieNumerique,
  "Blanchiment des dents": medicalExaminationsObj.blanchimentDesDents,
  "Extraction dentaire": medicalExaminationsObj.extractionDentaire,
  Carie: medicalExaminationsObj.carie,
  "Radio panoramique": medicalExaminationsObj.radioPanoramique,
  "Radiographie dentaire": medicalExaminationsObj.radiographieDentaire,
  "Cône beam": medicalExaminationsObj.coneBeam,
  Détartrage: medicalExaminationsObj.detartrage,
  "Prothèse dentaire fixe ou amovible":
    medicalExaminationsObj.protheseDentaireFixeOuAmovible,
  "Prothèse sur implant": medicalExaminationsObj.protheseSurImplant,
  Prophylaxie: medicalExaminationsObj.prophylaxie,
  "Facette dentaire": medicalExaminationsObj.facetteDentaire,
  "Orthodontie pour adulte": medicalExaminationsObj.orthodontiePourAdulte,
  "Orthodontie pédiatrique": medicalExaminationsObj.orthodontiePediatrique,
  "Orthopédie dento-faciale": medicalExaminationsObj.orthopedieDentoFaciale,
  "Alignement dentaire invisible":
    medicalExaminationsObj.alignementDentaireInvisible,
  "Appareil dentaire": medicalExaminationsObj.appareilDentaire,
  "Dysfonctionnement temporo-mandibulaire (DTM)":
    medicalExaminationsObj.dysfonctionnementTemporoMandibulaireDtm,
  "Gouttière dentaire": medicalExaminationsObj.gouttiereDentaire,
  "Orthèse d'avancée mandibulaire (OAM)":
    medicalExaminationsObj.ortheseDavanceeMandibulaireOam,
  "Technique linguale": medicalExaminationsObj.techniqueLinguale,
  Occlusodontie: medicalExaminationsObj.occlusodontie,
};
